"use client";

import createClient, { type Middleware } from "openapi-fetch";
import type { paths } from "./schema";

/**
 * A typed client for the Go backend.
 *
 * The types come from the OpenAPI spec the backend itself serves, generated by
 * `npm run api:types` — so a path, a param or a field that the server renamed
 * is a compile error here, not a 404 at runtime. The frontend does not yet call
 * this in anger (the store still runs in memory); this is the seam the wiring
 * step plugs into.
 *
 * The base URL is the same-origin proxy path. next.config.ts rewrites
 * /api/v1/* to the backend, so there is no CORS and no host to configure.
 */

const TOKEN_KEY = "wit-session-token";

/** The bearer token from the last backend login, or null. */
export function getSessionToken(): string | null {
  if (typeof window === "undefined") return null;
  try {
    return window.localStorage.getItem(TOKEN_KEY);
  } catch {
    return null; // localStorage can throw in private mode
  }
}

/** Remember (or, with null, forget) the backend session token. */
export function setSessionToken(token: string | null) {
  if (typeof window === "undefined") return;
  try {
    if (token) window.localStorage.setItem(TOKEN_KEY, token);
    else window.localStorage.removeItem(TOKEN_KEY);
  } catch {
    /* ignore: a client that cannot persist still works for this session */
  }
}

// Attach the bearer token to every request that has one. Kept as middleware so
// a single login updates every later call without threading the token through.
const auth: Middleware = {
  onRequest({ request }) {
    const token = getSessionToken();
    if (token) request.headers.set("Authorization", `Bearer ${token}`);
    return request;
  },
};

export const api = createClient<paths>({ baseUrl: "/api/v1" });
api.use(auth);

/**
 * Log in against the backend and remember the session token. Returns the user
 * on success; throws with the server's message on failure so a caller can show
 * it. This is the one call that must run before any authenticated request.
 */
export async function login(email: string, password: string) {
  const { data, error } = await api.POST("/auth/login", {
    body: { email, password },
  });
  if (error || !data) {
    throw new Error(
      (error as { error?: string })?.error ?? "sign-in failed"
    );
  }
  setSessionToken(data.token);
  return data.user;
}

/** Revoke the current session on the server and forget the token locally. */
export async function logout() {
  if (getSessionToken()) await api.POST("/auth/logout");
  setSessionToken(null);
}
