-- Who changed what. The session layer resolves every write to a user; until now
-- nothing recorded it, so "who moved this task out of the sprint" or "who
-- deleted sprint 7" had no answer. This table is that answer.
--
-- It is deliberately append-only and denormalised: the actor's email and the
-- target's kind/id are copied in, not referenced, so the log still reads true
-- after the user or the target is deleted. A foreign key would either block the
-- delete or cascade the history away — both wrong for an audit trail.
CREATE TABLE activity_log (
    id          BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    actor_id    TEXT        NOT NULL,
    actor_email TEXT        NOT NULL,
    -- create | update | delete, and the rare domain action.
    action      TEXT        NOT NULL,
    -- The kind of thing acted on (clients, projects, modules, sprints, ...) and
    -- its id, as text so the row does not depend on the target's table.
    target_kind TEXT        NOT NULL,
    target_id   TEXT        NOT NULL DEFAULT '',
    -- Method and path, so the exact operation is recoverable even for actions
    -- the kind/id pair does not capture.
    method      TEXT        NOT NULL,
    path        TEXT        NOT NULL
);

-- The log is read newest-first, and filtered by target when asking "what
-- happened to this one thing".
CREATE INDEX activity_log_occurred_at_idx ON activity_log (occurred_at DESC, id DESC);
CREATE INDEX activity_log_target_idx ON activity_log (target_kind, target_id, occurred_at DESC);
