// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: activity.sql

package db

import (
	"context"
)

const insertActivity = `-- name: InsertActivity :exec
INSERT INTO activity_log (actor_id, actor_email, action, target_kind, target_id, method, path)
VALUES (
    $1, $2, $3,
    $4, $5, $6, $7
)
`

type InsertActivityParams struct {
	ActorID    string `json:"actorId"`
	ActorEmail string `json:"actorEmail"`
	Action     string `json:"action"`
	TargetKind string `json:"targetKind"`
	TargetID   string `json:"targetId"`
	Method     string `json:"method"`
	Path       string `json:"path"`
}

func (q *Queries) InsertActivity(ctx context.Context, arg InsertActivityParams) error {
	_, err := q.db.Exec(ctx, insertActivity,
		arg.ActorID,
		arg.ActorEmail,
		arg.Action,
		arg.TargetKind,
		arg.TargetID,
		arg.Method,
		arg.Path,
	)
	return err
}

const listActivity = `-- name: ListActivity :many
SELECT id, occurred_at, actor_id, actor_email, action, target_kind, target_id, method, path
FROM activity_log
ORDER BY occurred_at DESC, id DESC
LIMIT $2 OFFSET $1
`

type ListActivityParams struct {
	Off int32 `json:"off"`
	Lim int32 `json:"lim"`
}

func (q *Queries) ListActivity(ctx context.Context, arg ListActivityParams) ([]ActivityLog, error) {
	rows, err := q.db.Query(ctx, listActivity, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActivityLog{}
	for rows.Next() {
		var i ActivityLog
		if err := rows.Scan(
			&i.ID,
			&i.OccurredAt,
			&i.ActorID,
			&i.ActorEmail,
			&i.Action,
			&i.TargetKind,
			&i.TargetID,
			&i.Method,
			&i.Path,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActivityForTarget = `-- name: ListActivityForTarget :many
SELECT id, occurred_at, actor_id, actor_email, action, target_kind, target_id, method, path
FROM activity_log
WHERE target_kind = $1 AND target_id = $2
ORDER BY occurred_at DESC, id DESC
LIMIT $4 OFFSET $3
`

type ListActivityForTargetParams struct {
	TargetKind string `json:"targetKind"`
	TargetID   string `json:"targetId"`
	Off        int32  `json:"off"`
	Lim        int32  `json:"lim"`
}

func (q *Queries) ListActivityForTarget(ctx context.Context, arg ListActivityForTargetParams) ([]ActivityLog, error) {
	rows, err := q.db.Query(ctx, listActivityForTarget,
		arg.TargetKind,
		arg.TargetID,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActivityLog{}
	for rows.Next() {
		var i ActivityLog
		if err := rows.Scan(
			&i.ID,
			&i.OccurredAt,
			&i.ActorID,
			&i.ActorEmail,
			&i.Action,
			&i.TargetKind,
			&i.TargetID,
			&i.Method,
			&i.Path,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
