// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: clients_projects.sql

package db

import (
	"context"
)

const createClient = `-- name: CreateClient :one

INSERT INTO clients (
    id,
    name,
    industry,
    status,
    client_pic,
    wit_owner,
    contract_type,
    health,
    risk,
    notes,
    action_needed,
    ai_insight
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
)
RETURNING id, name, industry, status, client_pic, wit_owner, contract_type, health, risk, notes, action_needed, ai_insight, created_at, updated_at
`

type CreateClientParams struct {
	ID           string   `json:"id"`
	Name         string   `json:"name"`
	Industry     string   `json:"industry"`
	Status       string   `json:"status"`
	ClientPic    string   `json:"clientPic"`
	WitOwner     string   `json:"witOwner"`
	ContractType string   `json:"contractType"`
	Health       string   `json:"health"`
	Risk         string   `json:"risk"`
	Notes        string   `json:"notes"`
	ActionNeeded []string `json:"actionNeeded"`
	AiInsight    []byte   `json:"aiInsight"`
}

// ---------------------------------------------------------------- clients ---
func (q *Queries) CreateClient(ctx context.Context, arg CreateClientParams) (Client, error) {
	row := q.db.QueryRow(ctx, createClient,
		arg.ID,
		arg.Name,
		arg.Industry,
		arg.Status,
		arg.ClientPic,
		arg.WitOwner,
		arg.ContractType,
		arg.Health,
		arg.Risk,
		arg.Notes,
		arg.ActionNeeded,
		arg.AiInsight,
	)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Industry,
		&i.Status,
		&i.ClientPic,
		&i.WitOwner,
		&i.ContractType,
		&i.Health,
		&i.Risk,
		&i.Notes,
		&i.ActionNeeded,
		&i.AiInsight,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createProject = `-- name: CreateProject :one

INSERT INTO projects (
    id,
    client_id,
    name,
    objective,
    status
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, client_id, name, objective, status, created_at, updated_at
`

type CreateProjectParams struct {
	ID        string `json:"id"`
	ClientID  string `json:"clientId"`
	Name      string `json:"name"`
	Objective string `json:"objective"`
	Status    string `json:"status"`
}

// --------------------------------------------------------------- projects ---
func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.ID,
		arg.ClientID,
		arg.Name,
		arg.Objective,
		arg.Status,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Name,
		&i.Objective,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteClient = `-- name: DeleteClient :exec
DELETE FROM clients
WHERE id = $1
`

func (q *Queries) DeleteClient(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteClient, id)
	return err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM projects
WHERE id = $1
`

func (q *Queries) DeleteProject(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteProject, id)
	return err
}

const getClient = `-- name: GetClient :one
SELECT id, name, industry, status, client_pic, wit_owner, contract_type, health, risk, notes, action_needed, ai_insight, created_at, updated_at FROM clients
WHERE id = $1
`

func (q *Queries) GetClient(ctx context.Context, id string) (Client, error) {
	row := q.db.QueryRow(ctx, getClient, id)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Industry,
		&i.Status,
		&i.ClientPic,
		&i.WitOwner,
		&i.ContractType,
		&i.Health,
		&i.Risk,
		&i.Notes,
		&i.ActionNeeded,
		&i.AiInsight,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProject = `-- name: GetProject :one
SELECT id, client_id, name, objective, status, created_at, updated_at FROM projects
WHERE id = $1
`

func (q *Queries) GetProject(ctx context.Context, id string) (Project, error) {
	row := q.db.QueryRow(ctx, getProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Name,
		&i.Objective,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listClients = `-- name: ListClients :many
SELECT id, name, industry, status, client_pic, wit_owner, contract_type, health, risk, notes, action_needed, ai_insight, created_at, updated_at FROM clients
ORDER BY name
`

func (q *Queries) ListClients(ctx context.Context) ([]Client, error) {
	rows, err := q.db.Query(ctx, listClients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Client{}
	for rows.Next() {
		var i Client
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Industry,
			&i.Status,
			&i.ClientPic,
			&i.WitOwner,
			&i.ContractType,
			&i.Health,
			&i.Risk,
			&i.Notes,
			&i.ActionNeeded,
			&i.AiInsight,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjects = `-- name: ListProjects :many
SELECT id, client_id, name, objective, status, created_at, updated_at FROM projects
ORDER BY name
`

func (q *Queries) ListProjects(ctx context.Context) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.Name,
			&i.Objective,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsByClient = `-- name: ListProjectsByClient :many
SELECT id, client_id, name, objective, status, created_at, updated_at FROM projects
WHERE client_id = $1
ORDER BY name
`

func (q *Queries) ListProjectsByClient(ctx context.Context, clientID string) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjectsByClient, clientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.Name,
			&i.Objective,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateClient = `-- name: UpdateClient :one
UPDATE clients
SET
    name          = $2,
    industry      = $3,
    status        = $4,
    client_pic    = $5,
    wit_owner     = $6,
    contract_type = $7,
    health        = $8,
    risk          = $9,
    notes         = $10,
    action_needed = $11,
    ai_insight    = $12,
    updated_at    = now()
WHERE id = $1
RETURNING id, name, industry, status, client_pic, wit_owner, contract_type, health, risk, notes, action_needed, ai_insight, created_at, updated_at
`

type UpdateClientParams struct {
	ID           string   `json:"id"`
	Name         string   `json:"name"`
	Industry     string   `json:"industry"`
	Status       string   `json:"status"`
	ClientPic    string   `json:"clientPic"`
	WitOwner     string   `json:"witOwner"`
	ContractType string   `json:"contractType"`
	Health       string   `json:"health"`
	Risk         string   `json:"risk"`
	Notes        string   `json:"notes"`
	ActionNeeded []string `json:"actionNeeded"`
	AiInsight    []byte   `json:"aiInsight"`
}

func (q *Queries) UpdateClient(ctx context.Context, arg UpdateClientParams) (Client, error) {
	row := q.db.QueryRow(ctx, updateClient,
		arg.ID,
		arg.Name,
		arg.Industry,
		arg.Status,
		arg.ClientPic,
		arg.WitOwner,
		arg.ContractType,
		arg.Health,
		arg.Risk,
		arg.Notes,
		arg.ActionNeeded,
		arg.AiInsight,
	)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Industry,
		&i.Status,
		&i.ClientPic,
		&i.WitOwner,
		&i.ContractType,
		&i.Health,
		&i.Risk,
		&i.Notes,
		&i.ActionNeeded,
		&i.AiInsight,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET
    client_id  = $2,
    name       = $3,
    objective  = $4,
    status     = $5,
    updated_at = now()
WHERE id = $1
RETURNING id, client_id, name, objective, status, created_at, updated_at
`

type UpdateProjectParams struct {
	ID        string `json:"id"`
	ClientID  string `json:"clientId"`
	Name      string `json:"name"`
	Objective string `json:"objective"`
	Status    string `json:"status"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject,
		arg.ID,
		arg.ClientID,
		arg.Name,
		arg.Objective,
		arg.Status,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Name,
		&i.Objective,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
