// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: exports.sql

package db

import (
	"context"
)

const exportClients = `-- name: ExportClients :many

SELECT id, name, industry, status, health, risk, contract_type,
       (archived_at IS NOT NULL)::bool AS archived
FROM clients
ORDER BY name, id
`

type ExportClientsRow struct {
	ID           string `json:"id"`
	Name         string `json:"name"`
	Industry     string `json:"industry"`
	Status       string `json:"status"`
	Health       string `json:"health"`
	Risk         string `json:"risk"`
	ContractType string `json:"contractType"`
	Archived     bool   `json:"archived"`
}

// Unbounded, ordered reads for CSV export. Deliberately not paginated: an export
// is the whole set, streamed row by row so a large one does not build in memory.
func (q *Queries) ExportClients(ctx context.Context) ([]ExportClientsRow, error) {
	rows, err := q.db.Query(ctx, exportClients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExportClientsRow{}
	for rows.Next() {
		var i ExportClientsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Industry,
			&i.Status,
			&i.Health,
			&i.Risk,
			&i.ContractType,
			&i.Archived,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportModuleTasks = `-- name: ExportModuleTasks :many
SELECT t.id, s.number AS sprint_number, t.title, t.component_name,
       t.board_column, t.priority, t.estimate,
       COALESCE(m.name, '') AS assignee
FROM tasks t
JOIN sprints s ON s.id = t.sprint_id
LEFT JOIN members m ON m.id = t.assignee_id
WHERE s.module_id = $1
ORDER BY s.number, t.created_at, t.id
`

type ExportModuleTasksRow struct {
	ID            string `json:"id"`
	SprintNumber  int32  `json:"sprintNumber"`
	Title         string `json:"title"`
	ComponentName string `json:"componentName"`
	BoardColumn   string `json:"boardColumn"`
	Priority      string `json:"priority"`
	Estimate      int32  `json:"estimate"`
	Assignee      string `json:"assignee"`
}

// Every task in a module, across its sprints, with the sprint number and the
// assignee's name resolved — the task list a delivery lead exports for a report.
func (q *Queries) ExportModuleTasks(ctx context.Context, moduleID string) ([]ExportModuleTasksRow, error) {
	rows, err := q.db.Query(ctx, exportModuleTasks, moduleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExportModuleTasksRow{}
	for rows.Next() {
		var i ExportModuleTasksRow
		if err := rows.Scan(
			&i.ID,
			&i.SprintNumber,
			&i.Title,
			&i.ComponentName,
			&i.BoardColumn,
			&i.Priority,
			&i.Estimate,
			&i.Assignee,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
