// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"encoding/json"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type ActivityLog struct {
	ID         int64              `json:"id"`
	OccurredAt pgtype.Timestamptz `json:"occurredAt"`
	ActorID    string             `json:"actorId"`
	ActorEmail string             `json:"actorEmail"`
	Action     string             `json:"action"`
	TargetKind string             `json:"targetKind"`
	TargetID   string             `json:"targetId"`
	Method     string             `json:"method"`
	Path       string             `json:"path"`
}

type BacklogItem struct {
	ID                 string             `json:"id"`
	ModuleID           string             `json:"moduleId"`
	ComponentID        *string            `json:"componentId"`
	Title              string             `json:"title"`
	Story              string             `json:"story"`
	AcceptanceCriteria []string           `json:"acceptanceCriteria"`
	Type               string             `json:"type"`
	Priority           string             `json:"priority"`
	Readiness          string             `json:"readiness"`
	Estimate           int32              `json:"estimate"`
	AiSuggestions      []string           `json:"aiSuggestions"`
	CreatedAt          pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt          pgtype.Timestamptz `json:"updatedAt"`
}

type Client struct {
	ID           string             `json:"id"`
	Name         string             `json:"name"`
	Industry     string             `json:"industry"`
	Status       string             `json:"status"`
	ClientPic    string             `json:"clientPic"`
	WitOwner     string             `json:"witOwner"`
	ContractType string             `json:"contractType"`
	Health       string             `json:"health"`
	Risk         string             `json:"risk"`
	Notes        string             `json:"notes"`
	ActionNeeded []string           `json:"actionNeeded"`
	AiInsight    json.RawMessage    `json:"aiInsight"`
	CreatedAt    pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt    pgtype.Timestamptz `json:"updatedAt"`
}

type Component struct {
	ID        string             `json:"id"`
	ModuleID  string             `json:"moduleId"`
	Name      string             `json:"name"`
	Owner     string             `json:"owner"`
	Status    string             `json:"status"`
	Position  int32              `json:"position"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt pgtype.Timestamptz `json:"updatedAt"`
}

type Decision struct {
	ID        string             `json:"id"`
	ModuleID  string             `json:"moduleId"`
	DecidedOn time.Time          `json:"decidedOn"`
	Title     string             `json:"title"`
	Detail    string             `json:"detail"`
	Owner     string             `json:"owner"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt pgtype.Timestamptz `json:"updatedAt"`
}

type EmailVerificationToken struct {
	TokenHash  string             `json:"tokenHash"`
	UserID     string             `json:"userId"`
	ExpiresAt  pgtype.Timestamptz `json:"expiresAt"`
	ConsumedAt pgtype.Timestamptz `json:"consumedAt"`
	CreatedAt  pgtype.Timestamptz `json:"createdAt"`
}

type GeneratedReport struct {
	ID          string             `json:"id"`
	ModuleID    string             `json:"moduleId"`
	SprintID    *string            `json:"sprintId"`
	Type        string             `json:"type"`
	Template    string             `json:"template"`
	Period      string             `json:"period"`
	GeneratedOn time.Time          `json:"generatedOn"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt   pgtype.Timestamptz `json:"updatedAt"`
}

type MasterList struct {
	Key      string `json:"key"`
	Value    string `json:"value"`
	Position int32  `json:"position"`
}

type Member struct {
	ID           string             `json:"id"`
	Name         string             `json:"name"`
	Email        string             `json:"email"`
	Role         string             `json:"role"`
	RoleLabel    string             `json:"roleLabel"`
	SkillTags    []string           `json:"skillTags"`
	Allocation   int32              `json:"allocation"`
	CapacityDays float64            `json:"capacityDays"`
	Workload     int32              `json:"workload"`
	Status       string             `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt    pgtype.Timestamptz `json:"updatedAt"`
}

type Module struct {
	ID              string             `json:"id"`
	ProjectID       string             `json:"projectId"`
	ClientID        string             `json:"clientId"`
	Name            string             `json:"name"`
	Goal            string             `json:"goal"`
	Owner           string             `json:"owner"`
	DeliveryLead    string             `json:"deliveryLead"`
	Status          string             `json:"status"`
	Health          int32              `json:"health"`
	Risk            string             `json:"risk"`
	Velocity        int32              `json:"velocity"`
	BlockedCount    int32              `json:"blockedCount"`
	CurrentSprintID *string            `json:"currentSprintId"`
	AiInsight       json.RawMessage    `json:"aiInsight"`
	CreatedAt       pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt       pgtype.Timestamptz `json:"updatedAt"`
}

type PasswordResetToken struct {
	TokenHash  string             `json:"tokenHash"`
	UserID     string             `json:"userId"`
	ExpiresAt  pgtype.Timestamptz `json:"expiresAt"`
	ConsumedAt pgtype.Timestamptz `json:"consumedAt"`
	CreatedAt  pgtype.Timestamptz `json:"createdAt"`
}

type Project struct {
	ID        string             `json:"id"`
	ClientID  string             `json:"clientId"`
	Name      string             `json:"name"`
	Objective string             `json:"objective"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt pgtype.Timestamptz `json:"updatedAt"`
}

type ReportQueue struct {
	ID        string             `json:"id"`
	Title     string             `json:"title"`
	ModuleID  string             `json:"moduleId"`
	Client    string             `json:"client"`
	Type      string             `json:"type"`
	Template  string             `json:"template"`
	Due       *time.Time         `json:"due"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt pgtype.Timestamptz `json:"updatedAt"`
}

type ReportTemplate struct {
	ID         string             `json:"id"`
	Name       string             `json:"name"`
	Audience   string             `json:"audience"`
	Visibility string             `json:"visibility"`
	Sections   []string           `json:"sections"`
	CreatedAt  pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt  pgtype.Timestamptz `json:"updatedAt"`
}

type Role struct {
	ID          string          `json:"id"`
	Label       string          `json:"label"`
	Permissions json.RawMessage `json:"permissions"`
}

type Session struct {
	TokenHash string             `json:"tokenHash"`
	UserID    string             `json:"userId"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
	ExpiresAt pgtype.Timestamptz `json:"expiresAt"`
}

type Sprint struct {
	ID          string             `json:"id"`
	ModuleID    string             `json:"moduleId"`
	ComponentID *string            `json:"componentId"`
	Number      int32              `json:"number"`
	Name        string             `json:"name"`
	Goal        string             `json:"goal"`
	StartDate   *time.Time         `json:"startDate"`
	EndDate     *time.Time         `json:"endDate"`
	WorkingDays int32              `json:"workingDays"`
	DaysLeft    int32              `json:"daysLeft"`
	Status      string             `json:"status"`
	Committed   int32              `json:"committed"`
	Completed   int32              `json:"completed"`
	Progress    int32              `json:"progress"`
	Risk        string             `json:"risk"`
	CreatedAt   pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt   pgtype.Timestamptz `json:"updatedAt"`
}

type SprintBacklogItem struct {
	SprintID      string `json:"sprintId"`
	BacklogItemID string `json:"backlogItemId"`
	Position      int32  `json:"position"`
}

type SprintMember struct {
	SprintID     string  `json:"sprintId"`
	MemberID     string  `json:"memberId"`
	Allocation   int32   `json:"allocation"`
	CapacityDays float64 `json:"capacityDays"`
}

type Task struct {
	ID            string             `json:"id"`
	SprintID      string             `json:"sprintId"`
	BacklogItemID string             `json:"backlogItemId"`
	Title         string             `json:"title"`
	ComponentName string             `json:"componentName"`
	AssigneeID    *string            `json:"assigneeId"`
	Estimate      int32              `json:"estimate"`
	BoardColumn   string             `json:"boardColumn"`
	Priority      string             `json:"priority"`
	BlockedReason *string            `json:"blockedReason"`
	BlockedDays   *int32             `json:"blockedDays"`
	OffGoal       bool               `json:"offGoal"`
	CreatedAt     pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt     pgtype.Timestamptz `json:"updatedAt"`
}

type TaskDod struct {
	TaskID   string `json:"taskId"`
	Position int32  `json:"position"`
	Label    string `json:"label"`
	Done     bool   `json:"done"`
}

type User struct {
	ID               string             `json:"id"`
	Email            string             `json:"email"`
	PasswordHash     string             `json:"passwordHash"`
	Name             string             `json:"name"`
	Role             string             `json:"role"`
	MemberID         *string            `json:"memberId"`
	Status           string             `json:"status"`
	EmailVerifiedAt  pgtype.Timestamptz `json:"emailVerifiedAt"`
	CreatedAt        pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt        pgtype.Timestamptz `json:"updatedAt"`
	FailedLoginCount int32              `json:"failedLoginCount"`
	LockedUntil      pgtype.Timestamptz `json:"lockedUntil"`
}

type WorkspaceSetting struct {
	ID          bool               `json:"id"`
	Name        string             `json:"name"`
	Settings    json.RawMessage    `json:"settings"`
	DodTemplate []string           `json:"dodTemplate"`
	UpdatedAt   pgtype.Timestamptz `json:"updatedAt"`
}
