// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: modules_components.sql

package db

import (
	"context"
	"encoding/json"
)

const createComponent = `-- name: CreateComponent :one

INSERT INTO components (
    id,
    module_id,
    name,
    owner,
    status,
    position
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, module_id, name, owner, status, position, created_at, updated_at
`

type CreateComponentParams struct {
	ID       string `json:"id"`
	ModuleID string `json:"moduleId"`
	Name     string `json:"name"`
	Owner    string `json:"owner"`
	Status   string `json:"status"`
	Position int32  `json:"position"`
}

// ============================================================================
// components (UI "Component")
// ============================================================================
// position is chosen by the caller or computed under a row lock; see
// LockModuleForUpdate for why it cannot be computed inline.
func (q *Queries) CreateComponent(ctx context.Context, arg CreateComponentParams) (Component, error) {
	row := q.db.QueryRow(ctx, createComponent,
		arg.ID,
		arg.ModuleID,
		arg.Name,
		arg.Owner,
		arg.Status,
		arg.Position,
	)
	var i Component
	err := row.Scan(
		&i.ID,
		&i.ModuleID,
		&i.Name,
		&i.Owner,
		&i.Status,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createModule = `-- name: CreateModule :one

INSERT INTO modules (
    id,
    project_id,
    client_id,
    name,
    goal,
    owner,
    delivery_lead,
    status,
    health,
    risk,
    velocity,
    blocked_count,
    ai_insight
)
SELECT
    $1,
    pj.id,
    pj.client_id,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11::jsonb
FROM projects pj
WHERE pj.id = $12
RETURNING id, project_id, client_id, name, goal, owner, delivery_lead, status, health, risk, velocity, blocked_count, current_sprint_id, ai_insight, created_at, updated_at
`

type CreateModuleParams struct {
	ID           string          `json:"id"`
	Name         string          `json:"name"`
	Goal         string          `json:"goal"`
	Owner        string          `json:"owner"`
	DeliveryLead string          `json:"deliveryLead"`
	Status       string          `json:"status"`
	Health       int32           `json:"health"`
	Risk         string          `json:"risk"`
	Velocity     int32           `json:"velocity"`
	BlockedCount int32           `json:"blockedCount"`
	AiInsight    json.RawMessage `json:"aiInsight"`
	ProjectID    string          `json:"projectId"`
}

// ============================================================================
// modules (UI "Component")
// ============================================================================
// client_id is denormalised, so it is derived from the project rather than
// taken from the caller: the two can never disagree, and a module can only
// ever be reached (and cascaded) through the client that really owns it.
// No matching project means no row, which the handler turns into a 400.
// current_sprint_id is not settable here: a new module has no sprints, so any
// value would point at another module's.
func (q *Queries) CreateModule(ctx context.Context, arg CreateModuleParams) (Module, error) {
	row := q.db.QueryRow(ctx, createModule,
		arg.ID,
		arg.Name,
		arg.Goal,
		arg.Owner,
		arg.DeliveryLead,
		arg.Status,
		arg.Health,
		arg.Risk,
		arg.Velocity,
		arg.BlockedCount,
		arg.AiInsight,
		arg.ProjectID,
	)
	var i Module
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ClientID,
		&i.Name,
		&i.Goal,
		&i.Owner,
		&i.DeliveryLead,
		&i.Status,
		&i.Health,
		&i.Risk,
		&i.Velocity,
		&i.BlockedCount,
		&i.CurrentSprintID,
		&i.AiInsight,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteComponent = `-- name: DeleteComponent :exec
DELETE FROM components
WHERE id = $1
`

func (q *Queries) DeleteComponent(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteComponent, id)
	return err
}

const deleteModule = `-- name: DeleteModule :exec
DELETE FROM modules
WHERE id = $1
`

func (q *Queries) DeleteModule(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteModule, id)
	return err
}

const getComponent = `-- name: GetComponent :one
SELECT id, module_id, name, owner, status, position, created_at, updated_at FROM components
WHERE id = $1
`

func (q *Queries) GetComponent(ctx context.Context, id string) (Component, error) {
	row := q.db.QueryRow(ctx, getComponent, id)
	var i Component
	err := row.Scan(
		&i.ID,
		&i.ModuleID,
		&i.Name,
		&i.Owner,
		&i.Status,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getModule = `-- name: GetModule :one
SELECT id, project_id, client_id, name, goal, owner, delivery_lead, status, health, risk, velocity, blocked_count, current_sprint_id, ai_insight, created_at, updated_at FROM modules
WHERE id = $1
`

func (q *Queries) GetModule(ctx context.Context, id string) (Module, error) {
	row := q.db.QueryRow(ctx, getModule, id)
	var i Module
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ClientID,
		&i.Name,
		&i.Goal,
		&i.Owner,
		&i.DeliveryLead,
		&i.Status,
		&i.Health,
		&i.Risk,
		&i.Velocity,
		&i.BlockedCount,
		&i.CurrentSprintID,
		&i.AiInsight,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listComponentsByModule = `-- name: ListComponentsByModule :many
SELECT id, module_id, name, owner, status, position, created_at, updated_at FROM components
WHERE module_id = $1
ORDER BY position, name, id
LIMIT $3 OFFSET $2
`

type ListComponentsByModuleParams struct {
	ModuleID string `json:"moduleId"`
	Off      int32  `json:"off"`
	Lim      int32  `json:"lim"`
}

func (q *Queries) ListComponentsByModule(ctx context.Context, arg ListComponentsByModuleParams) ([]Component, error) {
	rows, err := q.db.Query(ctx, listComponentsByModule, arg.ModuleID, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Component{}
	for rows.Next() {
		var i Component
		if err := rows.Scan(
			&i.ID,
			&i.ModuleID,
			&i.Name,
			&i.Owner,
			&i.Status,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModules = `-- name: ListModules :many
SELECT id, project_id, client_id, name, goal, owner, delivery_lead, status, health, risk, velocity, blocked_count, current_sprint_id, ai_insight, created_at, updated_at FROM modules
ORDER BY created_at, name, id
LIMIT $2 OFFSET $1
`

type ListModulesParams struct {
	Off int32 `json:"off"`
	Lim int32 `json:"lim"`
}

func (q *Queries) ListModules(ctx context.Context, arg ListModulesParams) ([]Module, error) {
	rows, err := q.db.Query(ctx, listModules, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Module{}
	for rows.Next() {
		var i Module
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ClientID,
			&i.Name,
			&i.Goal,
			&i.Owner,
			&i.DeliveryLead,
			&i.Status,
			&i.Health,
			&i.Risk,
			&i.Velocity,
			&i.BlockedCount,
			&i.CurrentSprintID,
			&i.AiInsight,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModulesByClient = `-- name: ListModulesByClient :many
SELECT id, project_id, client_id, name, goal, owner, delivery_lead, status, health, risk, velocity, blocked_count, current_sprint_id, ai_insight, created_at, updated_at FROM modules
WHERE client_id = $1
ORDER BY created_at, name, id
LIMIT $3 OFFSET $2
`

type ListModulesByClientParams struct {
	ClientID string `json:"clientId"`
	Off      int32  `json:"off"`
	Lim      int32  `json:"lim"`
}

func (q *Queries) ListModulesByClient(ctx context.Context, arg ListModulesByClientParams) ([]Module, error) {
	rows, err := q.db.Query(ctx, listModulesByClient, arg.ClientID, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Module{}
	for rows.Next() {
		var i Module
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ClientID,
			&i.Name,
			&i.Goal,
			&i.Owner,
			&i.DeliveryLead,
			&i.Status,
			&i.Health,
			&i.Risk,
			&i.Velocity,
			&i.BlockedCount,
			&i.CurrentSprintID,
			&i.AiInsight,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModulesByProject = `-- name: ListModulesByProject :many
SELECT id, project_id, client_id, name, goal, owner, delivery_lead, status, health, risk, velocity, blocked_count, current_sprint_id, ai_insight, created_at, updated_at FROM modules
WHERE project_id = $1
ORDER BY created_at, name, id
LIMIT $3 OFFSET $2
`

type ListModulesByProjectParams struct {
	ProjectID string `json:"projectId"`
	Off       int32  `json:"off"`
	Lim       int32  `json:"lim"`
}

func (q *Queries) ListModulesByProject(ctx context.Context, arg ListModulesByProjectParams) ([]Module, error) {
	rows, err := q.db.Query(ctx, listModulesByProject, arg.ProjectID, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Module{}
	for rows.Next() {
		var i Module
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ClientID,
			&i.Name,
			&i.Goal,
			&i.Owner,
			&i.DeliveryLead,
			&i.Status,
			&i.Health,
			&i.Risk,
			&i.Velocity,
			&i.BlockedCount,
			&i.CurrentSprintID,
			&i.AiInsight,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextComponentPosition = `-- name: NextComponentPosition :one
SELECT COALESCE(MAX(position), -1) + 1 AS next_position
FROM components
WHERE module_id = $1
`

func (q *Queries) NextComponentPosition(ctx context.Context, moduleID string) (int32, error) {
	row := q.db.QueryRow(ctx, nextComponentPosition, moduleID)
	var next_position int32
	err := row.Scan(&next_position)
	return next_position, err
}

const setModuleCurrentSprint = `-- name: SetModuleCurrentSprint :one
UPDATE modules p
SET
    current_sprint_id = $1,
    updated_at        = now()
WHERE p.id = $2
  AND (
      $1::text IS NULL
      OR EXISTS (
          SELECT 1 FROM sprints s
          WHERE s.id = $1 AND s.module_id = p.id
      )
  )
RETURNING id, project_id, client_id, name, goal, owner, delivery_lead, status, health, risk, velocity, blocked_count, current_sprint_id, ai_insight, created_at, updated_at
`

type SetModuleCurrentSprintParams struct {
	CurrentSprintID *string `json:"currentSprintId"`
	ID              string  `json:"id"`
}

// The pointer may only name a sprint of this very module. A mismatch matches
// no row, which the handler reports as a 400 rather than silently storing it.
func (q *Queries) SetModuleCurrentSprint(ctx context.Context, arg SetModuleCurrentSprintParams) (Module, error) {
	row := q.db.QueryRow(ctx, setModuleCurrentSprint, arg.CurrentSprintID, arg.ID)
	var i Module
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ClientID,
		&i.Name,
		&i.Goal,
		&i.Owner,
		&i.DeliveryLead,
		&i.Status,
		&i.Health,
		&i.Risk,
		&i.Velocity,
		&i.BlockedCount,
		&i.CurrentSprintID,
		&i.AiInsight,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateComponent = `-- name: UpdateComponent :one
UPDATE components
SET
    name       = COALESCE($1, name),
    owner      = COALESCE($2, owner),
    status     = COALESCE($3, status),
    position   = COALESCE($4, position),
    updated_at = now()
WHERE id = $5
RETURNING id, module_id, name, owner, status, position, created_at, updated_at
`

type UpdateComponentParams struct {
	Name     *string `json:"name"`
	Owner    *string `json:"owner"`
	Status   *string `json:"status"`
	Position *int32  `json:"position"`
	ID       string  `json:"id"`
}

func (q *Queries) UpdateComponent(ctx context.Context, arg UpdateComponentParams) (Component, error) {
	row := q.db.QueryRow(ctx, updateComponent,
		arg.Name,
		arg.Owner,
		arg.Status,
		arg.Position,
		arg.ID,
	)
	var i Component
	err := row.Scan(
		&i.ID,
		&i.ModuleID,
		&i.Name,
		&i.Owner,
		&i.Status,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateComponentStatus = `-- name: UpdateComponentStatus :one
UPDATE components
SET
    status     = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, module_id, name, owner, status, position, created_at, updated_at
`

type UpdateComponentStatusParams struct {
	ID     string `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateComponentStatus(ctx context.Context, arg UpdateComponentStatusParams) (Component, error) {
	row := q.db.QueryRow(ctx, updateComponentStatus, arg.ID, arg.Status)
	var i Component
	err := row.Scan(
		&i.ID,
		&i.ModuleID,
		&i.Name,
		&i.Owner,
		&i.Status,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateModule = `-- name: UpdateModule :one
UPDATE modules p
SET
    project_id    = COALESCE($1, p.project_id),
    client_id     = CASE
        WHEN $1::text IS NULL THEN p.client_id
        ELSE (SELECT pj.client_id FROM projects pj WHERE pj.id = $1)
    END,
    name          = COALESCE($2, p.name),
    goal          = COALESCE($3, p.goal),
    owner         = COALESCE($4, p.owner),
    delivery_lead = COALESCE($5, p.delivery_lead),
    status        = COALESCE($6, p.status),
    health        = COALESCE($7, p.health),
    risk          = COALESCE($8, p.risk),
    velocity      = COALESCE($9, p.velocity),
    blocked_count = COALESCE($10, p.blocked_count),
    ai_insight    = COALESCE($11::jsonb, p.ai_insight),
    updated_at    = now()
WHERE p.id = $12
RETURNING id, project_id, client_id, name, goal, owner, delivery_lead, status, health, risk, velocity, blocked_count, current_sprint_id, ai_insight, created_at, updated_at
`

type UpdateModuleParams struct {
	ProjectID    *string         `json:"projectId"`
	Name         *string         `json:"name"`
	Goal         *string         `json:"goal"`
	Owner        *string         `json:"owner"`
	DeliveryLead *string         `json:"deliveryLead"`
	Status       *string         `json:"status"`
	Health       *int32          `json:"health"`
	Risk         *string         `json:"risk"`
	Velocity     *int32          `json:"velocity"`
	BlockedCount *int32          `json:"blockedCount"`
	AiInsight    json.RawMessage `json:"aiInsight"`
	ID           string          `json:"id"`
}

// Partial update (see UpdateClient). client_id is never taken from the caller —
// it always follows whichever project the row ends up on.
// client_id is only recomputed when the module actually moves. Recomputing it
// unconditionally raced with "project moved to another client": the subquery
// read the pre-move snapshot while the row itself was re-read after the move,
// and the composite foreign key rejected the mismatched pair — failing a PATCH
// that never mentioned projectId.
func (q *Queries) UpdateModule(ctx context.Context, arg UpdateModuleParams) (Module, error) {
	row := q.db.QueryRow(ctx, updateModule,
		arg.ProjectID,
		arg.Name,
		arg.Goal,
		arg.Owner,
		arg.DeliveryLead,
		arg.Status,
		arg.Health,
		arg.Risk,
		arg.Velocity,
		arg.BlockedCount,
		arg.AiInsight,
		arg.ID,
	)
	var i Module
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ClientID,
		&i.Name,
		&i.Goal,
		&i.Owner,
		&i.DeliveryLead,
		&i.Status,
		&i.Health,
		&i.Risk,
		&i.Velocity,
		&i.BlockedCount,
		&i.CurrentSprintID,
		&i.AiInsight,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
