// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: products_modules.sql

package db

import (
	"context"
)

const createModule = `-- name: CreateModule :one

INSERT INTO modules (
    id,
    product_id,
    name,
    owner,
    status,
    position
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, product_id, name, owner, status, position, created_at, updated_at
`

type CreateModuleParams struct {
	ID        string `json:"id"`
	ProductID string `json:"productId"`
	Name      string `json:"name"`
	Owner     string `json:"owner"`
	Status    string `json:"status"`
	Position  int32  `json:"position"`
}

// ============================================================================
// modules (UI "Component")
// ============================================================================
func (q *Queries) CreateModule(ctx context.Context, arg CreateModuleParams) (Module, error) {
	row := q.db.QueryRow(ctx, createModule,
		arg.ID,
		arg.ProductID,
		arg.Name,
		arg.Owner,
		arg.Status,
		arg.Position,
	)
	var i Module
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Name,
		&i.Owner,
		&i.Status,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createProduct = `-- name: CreateProduct :one

INSERT INTO products (
    id,
    project_id,
    client_id,
    name,
    goal,
    owner,
    delivery_lead,
    status,
    health,
    risk,
    velocity,
    blocked_count,
    current_sprint_id,
    ai_insight
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14
)
RETURNING id, project_id, client_id, name, goal, owner, delivery_lead, status, health, risk, velocity, blocked_count, current_sprint_id, ai_insight, created_at, updated_at
`

type CreateProductParams struct {
	ID              string  `json:"id"`
	ProjectID       string  `json:"projectId"`
	ClientID        string  `json:"clientId"`
	Name            string  `json:"name"`
	Goal            string  `json:"goal"`
	Owner           string  `json:"owner"`
	DeliveryLead    string  `json:"deliveryLead"`
	Status          string  `json:"status"`
	Health          int32   `json:"health"`
	Risk            string  `json:"risk"`
	Velocity        int32   `json:"velocity"`
	BlockedCount    int32   `json:"blockedCount"`
	CurrentSprintID *string `json:"currentSprintId"`
	AiInsight       []byte  `json:"aiInsight"`
}

// ============================================================================
// products (UI "Module")
// ============================================================================
func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.ID,
		arg.ProjectID,
		arg.ClientID,
		arg.Name,
		arg.Goal,
		arg.Owner,
		arg.DeliveryLead,
		arg.Status,
		arg.Health,
		arg.Risk,
		arg.Velocity,
		arg.BlockedCount,
		arg.CurrentSprintID,
		arg.AiInsight,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ClientID,
		&i.Name,
		&i.Goal,
		&i.Owner,
		&i.DeliveryLead,
		&i.Status,
		&i.Health,
		&i.Risk,
		&i.Velocity,
		&i.BlockedCount,
		&i.CurrentSprintID,
		&i.AiInsight,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteModule = `-- name: DeleteModule :exec
DELETE FROM modules
WHERE id = $1
`

func (q *Queries) DeleteModule(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteModule, id)
	return err
}

const deleteProduct = `-- name: DeleteProduct :exec
DELETE FROM products
WHERE id = $1
`

func (q *Queries) DeleteProduct(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteProduct, id)
	return err
}

const getModule = `-- name: GetModule :one
SELECT id, product_id, name, owner, status, position, created_at, updated_at FROM modules
WHERE id = $1
`

func (q *Queries) GetModule(ctx context.Context, id string) (Module, error) {
	row := q.db.QueryRow(ctx, getModule, id)
	var i Module
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Name,
		&i.Owner,
		&i.Status,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProduct = `-- name: GetProduct :one
SELECT id, project_id, client_id, name, goal, owner, delivery_lead, status, health, risk, velocity, blocked_count, current_sprint_id, ai_insight, created_at, updated_at FROM products
WHERE id = $1
`

func (q *Queries) GetProduct(ctx context.Context, id string) (Product, error) {
	row := q.db.QueryRow(ctx, getProduct, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ClientID,
		&i.Name,
		&i.Goal,
		&i.Owner,
		&i.DeliveryLead,
		&i.Status,
		&i.Health,
		&i.Risk,
		&i.Velocity,
		&i.BlockedCount,
		&i.CurrentSprintID,
		&i.AiInsight,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listModulesByProduct = `-- name: ListModulesByProduct :many
SELECT id, product_id, name, owner, status, position, created_at, updated_at FROM modules
WHERE product_id = $1
ORDER BY position, name
`

func (q *Queries) ListModulesByProduct(ctx context.Context, productID string) ([]Module, error) {
	rows, err := q.db.Query(ctx, listModulesByProduct, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Module{}
	for rows.Next() {
		var i Module
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Name,
			&i.Owner,
			&i.Status,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProducts = `-- name: ListProducts :many
SELECT id, project_id, client_id, name, goal, owner, delivery_lead, status, health, risk, velocity, blocked_count, current_sprint_id, ai_insight, created_at, updated_at FROM products
ORDER BY created_at, name
`

func (q *Queries) ListProducts(ctx context.Context) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ClientID,
			&i.Name,
			&i.Goal,
			&i.Owner,
			&i.DeliveryLead,
			&i.Status,
			&i.Health,
			&i.Risk,
			&i.Velocity,
			&i.BlockedCount,
			&i.CurrentSprintID,
			&i.AiInsight,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsByClient = `-- name: ListProductsByClient :many
SELECT id, project_id, client_id, name, goal, owner, delivery_lead, status, health, risk, velocity, blocked_count, current_sprint_id, ai_insight, created_at, updated_at FROM products
WHERE client_id = $1
ORDER BY created_at, name
`

func (q *Queries) ListProductsByClient(ctx context.Context, clientID string) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProductsByClient, clientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ClientID,
			&i.Name,
			&i.Goal,
			&i.Owner,
			&i.DeliveryLead,
			&i.Status,
			&i.Health,
			&i.Risk,
			&i.Velocity,
			&i.BlockedCount,
			&i.CurrentSprintID,
			&i.AiInsight,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsByProject = `-- name: ListProductsByProject :many
SELECT id, project_id, client_id, name, goal, owner, delivery_lead, status, health, risk, velocity, blocked_count, current_sprint_id, ai_insight, created_at, updated_at FROM products
WHERE project_id = $1
ORDER BY created_at, name
`

func (q *Queries) ListProductsByProject(ctx context.Context, projectID string) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProductsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ClientID,
			&i.Name,
			&i.Goal,
			&i.Owner,
			&i.DeliveryLead,
			&i.Status,
			&i.Health,
			&i.Risk,
			&i.Velocity,
			&i.BlockedCount,
			&i.CurrentSprintID,
			&i.AiInsight,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setProductCurrentSprint = `-- name: SetProductCurrentSprint :one
UPDATE products
SET
    current_sprint_id = $2,
    updated_at        = now()
WHERE id = $1
RETURNING id, project_id, client_id, name, goal, owner, delivery_lead, status, health, risk, velocity, blocked_count, current_sprint_id, ai_insight, created_at, updated_at
`

type SetProductCurrentSprintParams struct {
	ID              string  `json:"id"`
	CurrentSprintID *string `json:"currentSprintId"`
}

func (q *Queries) SetProductCurrentSprint(ctx context.Context, arg SetProductCurrentSprintParams) (Product, error) {
	row := q.db.QueryRow(ctx, setProductCurrentSprint, arg.ID, arg.CurrentSprintID)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ClientID,
		&i.Name,
		&i.Goal,
		&i.Owner,
		&i.DeliveryLead,
		&i.Status,
		&i.Health,
		&i.Risk,
		&i.Velocity,
		&i.BlockedCount,
		&i.CurrentSprintID,
		&i.AiInsight,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateModule = `-- name: UpdateModule :one
UPDATE modules
SET
    name       = $2,
    owner      = $3,
    status     = $4,
    position   = $5,
    updated_at = now()
WHERE id = $1
RETURNING id, product_id, name, owner, status, position, created_at, updated_at
`

type UpdateModuleParams struct {
	ID       string `json:"id"`
	Name     string `json:"name"`
	Owner    string `json:"owner"`
	Status   string `json:"status"`
	Position int32  `json:"position"`
}

func (q *Queries) UpdateModule(ctx context.Context, arg UpdateModuleParams) (Module, error) {
	row := q.db.QueryRow(ctx, updateModule,
		arg.ID,
		arg.Name,
		arg.Owner,
		arg.Status,
		arg.Position,
	)
	var i Module
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Name,
		&i.Owner,
		&i.Status,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateModuleStatus = `-- name: UpdateModuleStatus :one
UPDATE modules
SET
    status     = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, product_id, name, owner, status, position, created_at, updated_at
`

type UpdateModuleStatusParams struct {
	ID     string `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateModuleStatus(ctx context.Context, arg UpdateModuleStatusParams) (Module, error) {
	row := q.db.QueryRow(ctx, updateModuleStatus, arg.ID, arg.Status)
	var i Module
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Name,
		&i.Owner,
		&i.Status,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products
SET
    project_id    = $2,
    client_id     = $3,
    name          = $4,
    goal          = $5,
    owner         = $6,
    delivery_lead = $7,
    status        = $8,
    health        = $9,
    risk          = $10,
    velocity      = $11,
    blocked_count = $12,
    ai_insight    = $13,
    updated_at    = now()
WHERE id = $1
RETURNING id, project_id, client_id, name, goal, owner, delivery_lead, status, health, risk, velocity, blocked_count, current_sprint_id, ai_insight, created_at, updated_at
`

type UpdateProductParams struct {
	ID           string `json:"id"`
	ProjectID    string `json:"projectId"`
	ClientID     string `json:"clientId"`
	Name         string `json:"name"`
	Goal         string `json:"goal"`
	Owner        string `json:"owner"`
	DeliveryLead string `json:"deliveryLead"`
	Status       string `json:"status"`
	Health       int32  `json:"health"`
	Risk         string `json:"risk"`
	Velocity     int32  `json:"velocity"`
	BlockedCount int32  `json:"blockedCount"`
	AiInsight    []byte `json:"aiInsight"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.ID,
		arg.ProjectID,
		arg.ClientID,
		arg.Name,
		arg.Goal,
		arg.Owner,
		arg.DeliveryLead,
		arg.Status,
		arg.Health,
		arg.Risk,
		arg.Velocity,
		arg.BlockedCount,
		arg.AiInsight,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ClientID,
		&i.Name,
		&i.Goal,
		&i.Owner,
		&i.DeliveryLead,
		&i.Status,
		&i.Health,
		&i.Risk,
		&i.Velocity,
		&i.BlockedCount,
		&i.CurrentSprintID,
		&i.AiInsight,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
