// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	AddMasterValue(ctx context.Context, arg AddMasterValueParams) (MasterList, error)
	// --------------------------------------------------- sprint_backlog_items ---
	AddSprintBacklogItem(ctx context.Context, arg AddSprintBacklogItemParams) (SprintBacklogItem, error)
	// --------------------------------------------------------- sprint_members ---
	AddSprintMember(ctx context.Context, arg AddSprintMemberParams) (SprintMember, error)
	// ---------------------------------------------------------- backlog_items ---
	CreateBacklogItem(ctx context.Context, arg CreateBacklogItemParams) (BacklogItem, error)
	// ---------------------------------------------------------------- clients ---
	CreateClient(ctx context.Context, arg CreateClientParams) (Client, error)
	// -------------------------------------------------------------- decisions ---
	CreateDecision(ctx context.Context, arg CreateDecisionParams) (Decision, error)
	// ------------------------------------------------------ generated_reports ---
	CreateGeneratedReport(ctx context.Context, arg CreateGeneratedReportParams) (GeneratedReport, error)
	// ---------------------------------------------------------------- members ---
	CreateMember(ctx context.Context, arg CreateMemberParams) (Member, error)
	// ============================================================================
	// modules (UI "Component")
	// ============================================================================
	CreateModule(ctx context.Context, arg CreateModuleParams) (Module, error)
	// ============================================================================
	// products (UI "Module")
	// ============================================================================
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	// --------------------------------------------------------------- projects ---
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	CreateReportQueueItem(ctx context.Context, arg CreateReportQueueItemParams) (ReportQueue, error)
	CreateSprint(ctx context.Context, arg CreateSprintParams) (Sprint, error)
	// Sprints, sprint membership, sprint backlog and the product backlog.
	// Naming note: products = UI "Module", modules = UI "Component".
	// ---------------------------------------------------------------- sprints ---
	// Assigns the next sprint number for the product inside the INSERT itself, so
	// concurrent creates cannot both read the same MAX(number). The UNIQUE
	// (product_id, number) constraint is still the final arbiter; the caller
	// retries on a unique violation.
	CreateSprintAutoNumber(ctx context.Context, arg CreateSprintAutoNumberParams) (Sprint, error)
	// ------------------------------------------------------------------ tasks ---
	CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error)
	DeleteBacklogItem(ctx context.Context, id string) error
	DeleteClient(ctx context.Context, id string) error
	DeleteDecision(ctx context.Context, id string) error
	DeleteMasterValue(ctx context.Context, arg DeleteMasterValueParams) error
	DeleteMember(ctx context.Context, id string) error
	DeleteModule(ctx context.Context, id string) error
	DeleteProduct(ctx context.Context, id string) error
	DeleteProject(ctx context.Context, id string) error
	DeleteReportQueueItem(ctx context.Context, id string) error
	DeleteReportTemplate(ctx context.Context, id string) error
	DeleteSprint(ctx context.Context, id string) error
	DeleteTask(ctx context.Context, id string) error
	DeleteTaskDod(ctx context.Context, taskID string) error
	GetBacklogItem(ctx context.Context, id string) (BacklogItem, error)
	GetClient(ctx context.Context, id string) (Client, error)
	GetDecision(ctx context.Context, id string) (Decision, error)
	GetMember(ctx context.Context, id string) (Member, error)
	GetModule(ctx context.Context, id string) (Module, error)
	GetProduct(ctx context.Context, id string) (Product, error)
	GetProject(ctx context.Context, id string) (Project, error)
	GetSprint(ctx context.Context, id string) (Sprint, error)
	GetTask(ctx context.Context, id string) (Task, error)
	// ------------------------------------------------------ workspace_settings --
	GetWorkspaceSettings(ctx context.Context) (WorkspaceSetting, error)
	ListBacklogItemsByModule(ctx context.Context, moduleID *string) ([]BacklogItem, error)
	ListBacklogItemsByProduct(ctx context.Context, productID string) ([]BacklogItem, error)
	ListClients(ctx context.Context) ([]Client, error)
	ListDecisionsByProduct(ctx context.Context, productID string) ([]Decision, error)
	ListGeneratedReportsByProduct(ctx context.Context, productID string) ([]GeneratedReport, error)
	// ----------------------------------------------------------- master_lists ---
	ListMasterValues(ctx context.Context, key string) ([]MasterList, error)
	ListMembers(ctx context.Context) ([]Member, error)
	ListModulesByProduct(ctx context.Context, productID string) ([]Module, error)
	ListProducts(ctx context.Context) ([]Product, error)
	ListProductsByClient(ctx context.Context, clientID string) ([]Product, error)
	ListProductsByProject(ctx context.Context, projectID string) ([]Product, error)
	ListProjects(ctx context.Context) ([]Project, error)
	ListProjectsByClient(ctx context.Context, clientID string) ([]Project, error)
	// ----------------------------------------------------------- report_queue ---
	ListReportQueue(ctx context.Context) ([]ReportQueue, error)
	// ------------------------------------------------------- report_templates ---
	ListReportTemplates(ctx context.Context) ([]ReportTemplate, error)
	// ------------------------------------------------------------------ roles ---
	ListRoles(ctx context.Context) ([]Role, error)
	ListSprintBacklogItems(ctx context.Context, sprintID string) ([]ListSprintBacklogItemsRow, error)
	ListSprintMembers(ctx context.Context, sprintID string) ([]ListSprintMembersRow, error)
	ListSprintsByModule(ctx context.Context, moduleID *string) ([]Sprint, error)
	ListSprintsByProduct(ctx context.Context, productID string) ([]Sprint, error)
	ListTaskDod(ctx context.Context, taskID string) ([]TaskDod, error)
	ListTasksByBacklogItem(ctx context.Context, backlogItemID string) ([]Task, error)
	ListTasksBySprint(ctx context.Context, sprintID string) ([]Task, error)
	MarkGeneratedReportSent(ctx context.Context, id string) (GeneratedReport, error)
	MoveTask(ctx context.Context, arg MoveTaskParams) (Task, error)
	NextSprintNumber(ctx context.Context, productID string) (int32, error)
	RemoveSprintBacklogItem(ctx context.Context, arg RemoveSprintBacklogItemParams) error
	RemoveSprintMember(ctx context.Context, arg RemoveSprintMemberParams) error
	SetProductCurrentSprint(ctx context.Context, arg SetProductCurrentSprintParams) (Product, error)
	// --------------------------------------------------------------- task_dod ---
	SetTaskDodItem(ctx context.Context, arg SetTaskDodItemParams) (TaskDod, error)
	ToggleTaskDodItem(ctx context.Context, arg ToggleTaskDodItemParams) (TaskDod, error)
	UpdateBacklogItem(ctx context.Context, arg UpdateBacklogItemParams) (BacklogItem, error)
	UpdateClient(ctx context.Context, arg UpdateClientParams) (Client, error)
	UpdateDecision(ctx context.Context, arg UpdateDecisionParams) (Decision, error)
	UpdateMember(ctx context.Context, arg UpdateMemberParams) (Member, error)
	UpdateModule(ctx context.Context, arg UpdateModuleParams) (Module, error)
	UpdateModuleStatus(ctx context.Context, arg UpdateModuleStatusParams) (Module, error)
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error)
	UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error)
	UpdateReportQueueStatus(ctx context.Context, arg UpdateReportQueueStatusParams) (ReportQueue, error)
	UpdateSprint(ctx context.Context, arg UpdateSprintParams) (Sprint, error)
	UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error)
	UpsertReportTemplate(ctx context.Context, arg UpsertReportTemplateParams) (ReportTemplate, error)
	UpsertRole(ctx context.Context, arg UpsertRoleParams) (Role, error)
	UpsertWorkspaceSettings(ctx context.Context, arg UpsertWorkspaceSettingsParams) (WorkspaceSetting, error)
}

var _ Querier = (*Queries)(nil)
