// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	AddMasterValue(ctx context.Context, arg AddMasterValueParams) (MasterList, error)
	// --------------------------------------------------- sprint_backlog_items ---
	// The JOIN is the guard: an item may only be pulled into a sprint of its own
	// module. A cross-module id matches no row, which the handler reports as a
	// 400 — before, it linked happily and leaked the other module's story text.
	// The position is chosen by the caller or computed under a row lock; see
	// LockSprintForUpdate for why it cannot be computed inline.
	AddSprintBacklogItem(ctx context.Context, arg AddSprintBacklogItemParams) (SprintBacklogItem, error)
	// --------------------------------------------------------- sprint_members ---
	AddSprintMember(ctx context.Context, arg AddSprintMemberParams) (SprintMember, error)
	// Consuming is a conditional UPDATE, not a read-then-write: two clicks on the
	// same link race, and only the one that flips consumed_at from NULL matches a
	// row. The loser gets no row and is told the link is already used.
	ConsumeVerificationToken(ctx context.Context, tokenHash string) (ConsumeVerificationTokenRow, error)
	// ---------------------------------------------------------- backlog_items ---
	CreateBacklogItem(ctx context.Context, arg CreateBacklogItemParams) (BacklogItem, error)
	// ---------------------------------------------------------------- clients ---
	CreateClient(ctx context.Context, arg CreateClientParams) (Client, error)
	// ============================================================================
	// components (UI "Component")
	// ============================================================================
	// position is chosen by the caller or computed under a row lock; see
	// LockModuleForUpdate for why it cannot be computed inline.
	CreateComponent(ctx context.Context, arg CreateComponentParams) (Component, error)
	// -------------------------------------------------------------- decisions ---
	CreateDecision(ctx context.Context, arg CreateDecisionParams) (Decision, error)
	// ------------------------------------------------------ generated_reports ---
	// A report may only cite a sprint of the module it reports on; without the
	// guard a report on one client's component could link to another client's sprint,
	// and following that link returned the other client's data.
	CreateGeneratedReport(ctx context.Context, arg CreateGeneratedReportParams) (GeneratedReport, error)
	// ---------------------------------------------------------------- members ---
	CreateMember(ctx context.Context, arg CreateMemberParams) (Member, error)
	// ============================================================================
	// modules (UI "Component")
	// ============================================================================
	// client_id is denormalised, so it is derived from the project rather than
	// taken from the caller: the two can never disagree, and a module can only
	// ever be reached (and cascaded) through the client that really owns it.
	// No matching project means no row, which the handler turns into a 400.
	// current_sprint_id is not settable here: a new module has no sprints, so any
	// value would point at another module's.
	CreateModule(ctx context.Context, arg CreateModuleParams) (Module, error)
	// --------------------------------------------------------------- projects ---
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	CreateReportQueueItem(ctx context.Context, arg CreateReportQueueItemParams) (ReportQueue, error)
	// --------------------------------------------------------------- sessions ---
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateSprint(ctx context.Context, arg CreateSprintParams) (Sprint, error)
	// ------------------------------------------------------------------ tasks ---
	// The JOIN keeps a task inside its own module: the backlog item it implements
	// must belong to the module that owns the sprint. A mismatch matches no row,
	// which the handler reports as a 400.
	CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error)
	// Users: authentication accounts, distinct from members.
	//
	// The password hash is confined to one query. Every read the API serialises
	// returns an explicit column list without it, so there is no path by which a
	// hash can be marshalled into a response; only GetUserForAuth selects it, and
	// its result is never written to the client.
	// status is the caller's decision because the two callers mean different
	// things: self-registration starts 'pending' until the address is proven,
	// while an admin-created account is born 'active' — the admin is vouching for
	// it, and with no mailer a pending account created this way could never sign
	// in at all. email_verified_at stays NULL either way until a real verify.
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	// ------------------------------------------------ email verification ---
	CreateVerificationToken(ctx context.Context, arg CreateVerificationTokenParams) (EmailVerificationToken, error)
	DeleteBacklogItem(ctx context.Context, id string) error
	DeleteClient(ctx context.Context, id string) error
	DeleteComponent(ctx context.Context, id string) error
	DeleteDecision(ctx context.Context, id string) error
	DeleteExpiredSessions(ctx context.Context) (int64, error)
	DeleteMasterValue(ctx context.Context, arg DeleteMasterValueParams) error
	DeleteMember(ctx context.Context, id string) error
	DeleteModule(ctx context.Context, id string) error
	DeleteProject(ctx context.Context, id string) error
	DeleteReportQueueItem(ctx context.Context, id string) error
	DeleteReportTemplate(ctx context.Context, id string) error
	DeleteSession(ctx context.Context, tokenHash string) (int64, error)
	DeleteSprint(ctx context.Context, id string) error
	DeleteTask(ctx context.Context, id string) error
	// Every DoD item on a task, used when the task itself is being removed.
	DeleteTaskDod(ctx context.Context, taskID string) error
	// One item, by position — so a checklist can shrink, not only grow.
	DeleteTaskDodItem(ctx context.Context, arg DeleteTaskDodItemParams) (int64, error)
	GetBacklogItem(ctx context.Context, id string) (BacklogItem, error)
	GetClient(ctx context.Context, id string) (Client, error)
	GetComponent(ctx context.Context, id string) (Component, error)
	GetDecision(ctx context.Context, id string) (Decision, error)
	GetMember(ctx context.Context, id string) (Member, error)
	GetModule(ctx context.Context, id string) (Module, error)
	GetProject(ctx context.Context, id string) (Project, error)
	// The middleware query: one indexed lookup resolves the bearer token to the
	// user and the permissions of their role. Expiry is checked here rather than
	// in Go so an expired session and a bogus token are indistinguishable.
	// password_hash is deliberately not selected (see TestPasswordHashNeverSerialised).
	GetSessionUser(ctx context.Context, tokenHash string) (GetSessionUserRow, error)
	GetSprint(ctx context.Context, id string) (Sprint, error)
	GetTask(ctx context.Context, id string) (Task, error)
	GetUser(ctx context.Context, id string) (GetUserRow, error)
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	// The only query that returns the hash. Used to verify a password; its result
	// must never be serialised to a client.
	GetUserForAuth(ctx context.Context, email string) (GetUserForAuthRow, error)
	GetVerificationToken(ctx context.Context, tokenHash string) (GetVerificationTokenRow, error)
	// ------------------------------------------------------ workspace_settings --
	GetWorkspaceSettings(ctx context.Context) (WorkspaceSetting, error)
	// Called before issuing a new link, so an earlier mail cannot still be used.
	InvalidateUserVerificationTokens(ctx context.Context, userID string) error
	ListBacklogItemsByComponent(ctx context.Context, arg ListBacklogItemsByComponentParams) ([]BacklogItem, error)
	ListBacklogItemsByModule(ctx context.Context, arg ListBacklogItemsByModuleParams) ([]BacklogItem, error)
	ListClients(ctx context.Context, arg ListClientsParams) ([]Client, error)
	ListComponentsByModule(ctx context.Context, arg ListComponentsByModuleParams) ([]Component, error)
	ListDecisionsByModule(ctx context.Context, arg ListDecisionsByModuleParams) ([]Decision, error)
	ListGeneratedReportsByModule(ctx context.Context, arg ListGeneratedReportsByModuleParams) ([]GeneratedReport, error)
	// ----------------------------------------------------------- master_lists ---
	ListMasterValues(ctx context.Context, arg ListMasterValuesParams) ([]MasterList, error)
	ListMembers(ctx context.Context, arg ListMembersParams) ([]Member, error)
	ListModules(ctx context.Context, arg ListModulesParams) ([]Module, error)
	ListModulesByClient(ctx context.Context, arg ListModulesByClientParams) ([]Module, error)
	ListModulesByProject(ctx context.Context, arg ListModulesByProjectParams) ([]Module, error)
	ListProjects(ctx context.Context, arg ListProjectsParams) ([]Project, error)
	ListProjectsByClient(ctx context.Context, arg ListProjectsByClientParams) ([]Project, error)
	// ----------------------------------------------------------- report_queue ---
	ListReportQueue(ctx context.Context, arg ListReportQueueParams) ([]ReportQueue, error)
	// ------------------------------------------------------- report_templates ---
	ListReportTemplates(ctx context.Context, arg ListReportTemplatesParams) ([]ReportTemplate, error)
	// ------------------------------------------------------------------ roles ---
	ListRoles(ctx context.Context, arg ListRolesParams) ([]Role, error)
	ListSprintBacklogItems(ctx context.Context, arg ListSprintBacklogItemsParams) ([]ListSprintBacklogItemsRow, error)
	ListSprintMembers(ctx context.Context, arg ListSprintMembersParams) ([]ListSprintMembersRow, error)
	// number is only unique per module, so it cannot order a cross-module list
	// on its own.
	ListSprintsByComponent(ctx context.Context, arg ListSprintsByComponentParams) ([]Sprint, error)
	// No id tiebreaker: UNIQUE (module_id, number) already makes this a total
	// order, and adding one costs the index-scan-backward plan.
	ListSprintsByModule(ctx context.Context, arg ListSprintsByModuleParams) ([]Sprint, error)
	ListTaskDod(ctx context.Context, arg ListTaskDodParams) ([]TaskDod, error)
	// Carries the assignee's name so the board need not fetch every member
	// separately — one query per lane instead of one per card. LEFT JOIN, not
	// JOIN: an unassigned task is a real state (assignee_id is nullable).
	ListTasksBySprint(ctx context.Context, arg ListTasksBySprintParams) ([]ListTasksBySprintRow, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error)
	// Taken before the sprint lock so the ordering matches the cascade's:
	// DELETE FROM modules reaches backlog_items before sprints, so locking the
	// sprint first and the item second is an AB-BA cycle that deadlocks every
	// concurrent parent delete.
	LockBacklogItemForShare(ctx context.Context, id string) (string, error)
	// Sprints, sprint membership, sprint backlog and the module backlog.
	// Naming note: modules = UI "Component", components = UI "Component".
	// ---------------------------------------------------------------- sprints ---
	// Serialises per-module sequencing (sprint numbers, component positions).
	// A single statement cannot do this for itself: under READ COMMITTED its
	// snapshot is fixed before any lock it takes, so concurrent statements all
	// read the same MAX() no matter how they queue. Taking the row lock in its own
	// statement, inside a transaction, is what makes the next read see the truth.
	//
	// FOR NO KEY UPDATE, not FOR UPDATE: only the latter conflicts with the
	// FOR KEY SHARE that every child insert's foreign-key check takes, which would
	// freeze unrelated endpoints (backlog, decisions, explicitly-numbered sprints)
	// for as long as one sequencing transaction runs.
	LockModuleForUpdate(ctx context.Context, id string) (string, error)
	LockSprintForUpdate(ctx context.Context, id string) (string, error)
	MarkGeneratedReportSent(ctx context.Context, id string) (GeneratedReport, error)
	MarkUserVerified(ctx context.Context, id string) (MarkUserVerifiedRow, error)
	MoveTask(ctx context.Context, arg MoveTaskParams) (Task, error)
	NextComponentPosition(ctx context.Context, moduleID string) (int32, error)
	NextSprintBacklogPosition(ctx context.Context, sprintID string) (int32, error)
	NextSprintNumber(ctx context.Context, moduleID string) (int32, error)
	RemoveSprintBacklogItem(ctx context.Context, arg RemoveSprintBacklogItemParams) error
	RemoveSprintMember(ctx context.Context, arg RemoveSprintMemberParams) error
	// The pointer may only name a sprint of this very module. A mismatch matches
	// no row, which the handler reports as a 400 rather than silently storing it.
	SetModuleCurrentSprint(ctx context.Context, arg SetModuleCurrentSprintParams) (Module, error)
	// set_config, not SET LOCAL: the latter cannot take a parameter. `true` scopes
	// it to the surrounding transaction.
	SetStatementTimeout(ctx context.Context, ms string) error
	// --------------------------------------------------------------- task_dod ---
	SetTaskDodItem(ctx context.Context, arg SetTaskDodItemParams) (TaskDod, error)
	ToggleTaskDodItem(ctx context.Context, arg ToggleTaskDodItemParams) (TaskDod, error)
	// Partial update (see UpdateClient).
	UpdateBacklogItem(ctx context.Context, arg UpdateBacklogItemParams) (BacklogItem, error)
	// Partial update: a NULL argument means "not supplied", so a column nobody
	// named is never rewritten. Two concurrent PATCHes of different fields both
	// land instead of the second silently reverting the first.
	UpdateClient(ctx context.Context, arg UpdateClientParams) (Client, error)
	UpdateComponent(ctx context.Context, arg UpdateComponentParams) (Component, error)
	UpdateComponentStatus(ctx context.Context, arg UpdateComponentStatusParams) (Component, error)
	// Partial update (see UpdateClient).
	UpdateDecision(ctx context.Context, arg UpdateDecisionParams) (Decision, error)
	// Partial update (see UpdateClient).
	UpdateMember(ctx context.Context, arg UpdateMemberParams) (Member, error)
	// Partial update (see UpdateClient). client_id is never taken from the caller —
	// it always follows whichever project the row ends up on.
	// client_id is only recomputed when the module actually moves. Recomputing it
	// unconditionally raced with "project moved to another client": the subquery
	// read the pre-move snapshot while the row itself was re-read after the move,
	// and the composite foreign key rejected the mismatched pair — failing a PATCH
	// that never mentioned projectId.
	UpdateModule(ctx context.Context, arg UpdateModuleParams) (Module, error)
	UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error)
	UpdateReportQueueStatus(ctx context.Context, arg UpdateReportQueueStatusParams) (ReportQueue, error)
	// Partial update (see UpdateClient).
	UpdateSprint(ctx context.Context, arg UpdateSprintParams) (Sprint, error)
	// Partial update (see UpdateClient): moving a card and renaming it at the same
	// moment no longer cancel each other out.
	UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error)
	UpsertReportTemplate(ctx context.Context, arg UpsertReportTemplateParams) (ReportTemplate, error)
	UpsertRole(ctx context.Context, arg UpsertRoleParams) (Role, error)
	UpsertWorkspaceSettings(ctx context.Context, arg UpsertWorkspaceSettingsParams) (WorkspaceSetting, error)
}

var _ Querier = (*Queries)(nil)
