// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rollups.sql

package db

import (
	"context"
)

const moduleRollup = `-- name: ModuleRollup :one
SELECT
    (SELECT count(*) FROM components    c  WHERE c.module_id  = $1) AS components,
    (SELECT count(*) FROM sprints       sp WHERE sp.module_id = $1) AS sprints,
    (SELECT count(*) FROM backlog_items b  WHERE b.module_id  = $1) AS backlog_items,
    (SELECT count(*) FROM sprints sp WHERE sp.module_id = $1 AND sp.status = 'active') AS active_sprints,
    (SELECT coalesce(sum(sp.committed), 0) FROM sprints sp WHERE sp.module_id = $1) AS committed_points,
    (SELECT coalesce(sum(sp.completed), 0) FROM sprints sp WHERE sp.module_id = $1) AS completed_points,
    (SELECT count(*)
       FROM tasks t
       JOIN sprints s ON s.id = t.sprint_id
      WHERE s.module_id = $1 AND t.board_column = 'blocked') AS blocked_tasks
`

type ModuleRollupRow struct {
	Components      int64       `json:"components"`
	Sprints         int64       `json:"sprints"`
	BacklogItems    int64       `json:"backlogItems"`
	ActiveSprints   int64       `json:"activeSprints"`
	CommittedPoints interface{} `json:"committedPoints"`
	CompletedPoints interface{} `json:"completedPoints"`
	BlockedTasks    int64       `json:"blockedTasks"`
}

// One module's numbers without walking its sprints: what the module overview and
// the project drill-down recompute per row. Every column is table-qualified so
// the shared module_id is never ambiguous.
func (q *Queries) ModuleRollup(ctx context.Context, moduleID string) (ModuleRollupRow, error) {
	row := q.db.QueryRow(ctx, moduleRollup, moduleID)
	var i ModuleRollupRow
	err := row.Scan(
		&i.Components,
		&i.Sprints,
		&i.BacklogItems,
		&i.ActiveSprints,
		&i.CommittedPoints,
		&i.CompletedPoints,
		&i.BlockedTasks,
	)
	return i, err
}

const portfolioRollup = `-- name: PortfolioRollup :one

SELECT
    (SELECT count(*) FROM clients WHERE archived_at IS NULL)   AS active_clients,
    (SELECT count(*) FROM projects)                            AS projects,
    (SELECT count(*) FROM modules)                             AS modules,
    (SELECT count(*) FROM modules WHERE risk <> 'low')         AS at_risk_modules,
    (SELECT count(*) FROM sprints WHERE status = 'active')     AS active_sprints,
    (SELECT count(*) FROM tasks   WHERE board_column = 'blocked') AS blocked_tasks,
    (SELECT count(*) FROM report_queue WHERE status <> 'done') AS reports_due
`

type PortfolioRollupRow struct {
	ActiveClients int64 `json:"activeClients"`
	Projects      int64 `json:"projects"`
	Modules       int64 `json:"modules"`
	AtRiskModules int64 `json:"atRiskModules"`
	ActiveSprints int64 `json:"activeSprints"`
	BlockedTasks  int64 `json:"blockedTasks"`
	ReportsDue    int64 `json:"reportsDue"`
}

// Aggregate reads. The frontend recomputes these by pulling whole collections
// and counting in the browser — the dashboard alone fires a GET per sprint. One
// query each, computed where the data lives.
// The home dashboard in a single request: the counters it used to sum by hand.
func (q *Queries) PortfolioRollup(ctx context.Context) (PortfolioRollupRow, error) {
	row := q.db.QueryRow(ctx, portfolioRollup)
	var i PortfolioRollupRow
	err := row.Scan(
		&i.ActiveClients,
		&i.Projects,
		&i.Modules,
		&i.AtRiskModules,
		&i.ActiveSprints,
		&i.BlockedTasks,
		&i.ReportsDue,
	)
	return i, err
}
