// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: snapshots.sql

package db

import (
	"context"
	"time"
)

const captureActiveSprintSnapshots = `-- name: CaptureActiveSprintSnapshots :execrows
INSERT INTO sprint_daily_snapshots (sprint_id, snapshot_on, remaining_points, completed_points)
SELECT id, CURRENT_DATE, GREATEST(committed - completed, 0), completed
FROM sprints
WHERE status = 'active'
ON CONFLICT (sprint_id, snapshot_on) DO UPDATE
SET remaining_points = EXCLUDED.remaining_points,
    completed_points = EXCLUDED.completed_points
`

// Records today's remaining and completed points for every active sprint, in
// one statement. Idempotent per day: run it hourly and the latest wins. A daily
// cron would hit POST /snapshots/capture; this is what it runs.
func (q *Queries) CaptureActiveSprintSnapshots(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, captureActiveSprintSnapshots)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listSprintBurndown = `-- name: ListSprintBurndown :many
SELECT snapshot_on, remaining_points, completed_points
FROM sprint_daily_snapshots
WHERE sprint_id = $1
ORDER BY snapshot_on
`

type ListSprintBurndownRow struct {
	SnapshotOn      time.Time `json:"snapshotOn"`
	RemainingPoints int32     `json:"remainingPoints"`
	CompletedPoints int32     `json:"completedPoints"`
}

// The recorded burn for one sprint, oldest first — the real series a chart draws
// instead of a synthesized straight line.
func (q *Queries) ListSprintBurndown(ctx context.Context, sprintID string) ([]ListSprintBurndownRow, error) {
	rows, err := q.db.Query(ctx, listSprintBurndown, sprintID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSprintBurndownRow{}
	for rows.Next() {
		var i ListSprintBurndownRow
		if err := rows.Scan(&i.SnapshotOn, &i.RemainingPoints, &i.CompletedPoints); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moduleVelocity = `-- name: ModuleVelocity :many
SELECT number, name, committed, completed
FROM sprints
WHERE module_id = $1 AND status IN ('review', 'done')
ORDER BY number
`

type ModuleVelocityRow struct {
	Number    int32  `json:"number"`
	Name      string `json:"name"`
	Committed int32  `json:"committed"`
	Completed int32  `json:"completed"`
}

// Completed points per finished sprint, in sprint order — velocity's trend,
// computed straight from the sprints table (no snapshot needed).
func (q *Queries) ModuleVelocity(ctx context.Context, moduleID string) ([]ModuleVelocityRow, error) {
	rows, err := q.db.Query(ctx, moduleVelocity, moduleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ModuleVelocityRow{}
	for rows.Next() {
		var i ModuleVelocityRow
		if err := rows.Scan(
			&i.Number,
			&i.Name,
			&i.Committed,
			&i.Completed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
