// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sprints_backlog.sql

package db

import (
	"context"
	"time"
)

const addSprintBacklogItem = `-- name: AddSprintBacklogItem :one

INSERT INTO sprint_backlog_items (
    sprint_id,
    backlog_item_id,
    position
) VALUES (
    $1, $2, $3
)
ON CONFLICT (sprint_id, backlog_item_id) DO UPDATE
SET position = EXCLUDED.position
RETURNING sprint_id, backlog_item_id, position
`

type AddSprintBacklogItemParams struct {
	SprintID      string `json:"sprintId"`
	BacklogItemID string `json:"backlogItemId"`
	Position      int32  `json:"position"`
}

// --------------------------------------------------- sprint_backlog_items ---
func (q *Queries) AddSprintBacklogItem(ctx context.Context, arg AddSprintBacklogItemParams) (SprintBacklogItem, error) {
	row := q.db.QueryRow(ctx, addSprintBacklogItem, arg.SprintID, arg.BacklogItemID, arg.Position)
	var i SprintBacklogItem
	err := row.Scan(&i.SprintID, &i.BacklogItemID, &i.Position)
	return i, err
}

const addSprintMember = `-- name: AddSprintMember :one

INSERT INTO sprint_members (
    sprint_id,
    member_id,
    allocation,
    capacity_days
) VALUES (
    $1, $2, $3, $4
)
ON CONFLICT (sprint_id, member_id) DO UPDATE
SET allocation    = EXCLUDED.allocation,
    capacity_days = EXCLUDED.capacity_days
RETURNING sprint_id, member_id, allocation, capacity_days
`

type AddSprintMemberParams struct {
	SprintID     string  `json:"sprintId"`
	MemberID     string  `json:"memberId"`
	Allocation   int32   `json:"allocation"`
	CapacityDays float64 `json:"capacityDays"`
}

// --------------------------------------------------------- sprint_members ---
func (q *Queries) AddSprintMember(ctx context.Context, arg AddSprintMemberParams) (SprintMember, error) {
	row := q.db.QueryRow(ctx, addSprintMember,
		arg.SprintID,
		arg.MemberID,
		arg.Allocation,
		arg.CapacityDays,
	)
	var i SprintMember
	err := row.Scan(
		&i.SprintID,
		&i.MemberID,
		&i.Allocation,
		&i.CapacityDays,
	)
	return i, err
}

const createBacklogItem = `-- name: CreateBacklogItem :one

INSERT INTO backlog_items (
    id,
    product_id,
    module_id,
    title,
    story,
    acceptance_criteria,
    type,
    priority,
    readiness,
    estimate,
    ai_suggestions
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
RETURNING id, product_id, module_id, title, story, acceptance_criteria, type, priority, readiness, estimate, ai_suggestions, created_at, updated_at
`

type CreateBacklogItemParams struct {
	ID                 string   `json:"id"`
	ProductID          string   `json:"productId"`
	ModuleID           *string  `json:"moduleId"`
	Title              string   `json:"title"`
	Story              string   `json:"story"`
	AcceptanceCriteria []string `json:"acceptanceCriteria"`
	Type               string   `json:"type"`
	Priority           string   `json:"priority"`
	Readiness          string   `json:"readiness"`
	Estimate           int32    `json:"estimate"`
	AiSuggestions      []string `json:"aiSuggestions"`
}

// ---------------------------------------------------------- backlog_items ---
func (q *Queries) CreateBacklogItem(ctx context.Context, arg CreateBacklogItemParams) (BacklogItem, error) {
	row := q.db.QueryRow(ctx, createBacklogItem,
		arg.ID,
		arg.ProductID,
		arg.ModuleID,
		arg.Title,
		arg.Story,
		arg.AcceptanceCriteria,
		arg.Type,
		arg.Priority,
		arg.Readiness,
		arg.Estimate,
		arg.AiSuggestions,
	)
	var i BacklogItem
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.ModuleID,
		&i.Title,
		&i.Story,
		&i.AcceptanceCriteria,
		&i.Type,
		&i.Priority,
		&i.Readiness,
		&i.Estimate,
		&i.AiSuggestions,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSprint = `-- name: CreateSprint :one


INSERT INTO sprints (
    id,
    product_id,
    module_id,
    number,
    name,
    goal,
    start_date,
    end_date,
    working_days,
    days_left,
    status,
    committed,
    completed,
    progress,
    risk
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15
)
RETURNING id, product_id, module_id, number, name, goal, start_date, end_date, working_days, days_left, status, committed, completed, progress, risk, created_at, updated_at
`

type CreateSprintParams struct {
	ID          string     `json:"id"`
	ProductID   string     `json:"productId"`
	ModuleID    *string    `json:"moduleId"`
	Number      int32      `json:"number"`
	Name        string     `json:"name"`
	Goal        string     `json:"goal"`
	StartDate   *time.Time `json:"startDate"`
	EndDate     *time.Time `json:"endDate"`
	WorkingDays int32      `json:"workingDays"`
	DaysLeft    int32      `json:"daysLeft"`
	Status      string     `json:"status"`
	Committed   int32      `json:"committed"`
	Completed   int32      `json:"completed"`
	Progress    int32      `json:"progress"`
	Risk        string     `json:"risk"`
}

// Sprints, sprint membership, sprint backlog and the product backlog.
// Naming note: products = UI "Module", modules = UI "Component".
// ---------------------------------------------------------------- sprints ---
func (q *Queries) CreateSprint(ctx context.Context, arg CreateSprintParams) (Sprint, error) {
	row := q.db.QueryRow(ctx, createSprint,
		arg.ID,
		arg.ProductID,
		arg.ModuleID,
		arg.Number,
		arg.Name,
		arg.Goal,
		arg.StartDate,
		arg.EndDate,
		arg.WorkingDays,
		arg.DaysLeft,
		arg.Status,
		arg.Committed,
		arg.Completed,
		arg.Progress,
		arg.Risk,
	)
	var i Sprint
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.ModuleID,
		&i.Number,
		&i.Name,
		&i.Goal,
		&i.StartDate,
		&i.EndDate,
		&i.WorkingDays,
		&i.DaysLeft,
		&i.Status,
		&i.Committed,
		&i.Completed,
		&i.Progress,
		&i.Risk,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBacklogItem = `-- name: DeleteBacklogItem :exec
DELETE FROM backlog_items
WHERE id = $1
`

func (q *Queries) DeleteBacklogItem(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteBacklogItem, id)
	return err
}

const deleteSprint = `-- name: DeleteSprint :exec
DELETE FROM sprints
WHERE id = $1
`

func (q *Queries) DeleteSprint(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteSprint, id)
	return err
}

const getBacklogItem = `-- name: GetBacklogItem :one
SELECT id, product_id, module_id, title, story, acceptance_criteria, type, priority, readiness, estimate, ai_suggestions, created_at, updated_at FROM backlog_items
WHERE id = $1
`

func (q *Queries) GetBacklogItem(ctx context.Context, id string) (BacklogItem, error) {
	row := q.db.QueryRow(ctx, getBacklogItem, id)
	var i BacklogItem
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.ModuleID,
		&i.Title,
		&i.Story,
		&i.AcceptanceCriteria,
		&i.Type,
		&i.Priority,
		&i.Readiness,
		&i.Estimate,
		&i.AiSuggestions,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSprint = `-- name: GetSprint :one
SELECT id, product_id, module_id, number, name, goal, start_date, end_date, working_days, days_left, status, committed, completed, progress, risk, created_at, updated_at FROM sprints
WHERE id = $1
`

func (q *Queries) GetSprint(ctx context.Context, id string) (Sprint, error) {
	row := q.db.QueryRow(ctx, getSprint, id)
	var i Sprint
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.ModuleID,
		&i.Number,
		&i.Name,
		&i.Goal,
		&i.StartDate,
		&i.EndDate,
		&i.WorkingDays,
		&i.DaysLeft,
		&i.Status,
		&i.Committed,
		&i.Completed,
		&i.Progress,
		&i.Risk,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBacklogItemsByModule = `-- name: ListBacklogItemsByModule :many
SELECT id, product_id, module_id, title, story, acceptance_criteria, type, priority, readiness, estimate, ai_suggestions, created_at, updated_at FROM backlog_items
WHERE module_id = $1
ORDER BY created_at DESC, id ASC
`

func (q *Queries) ListBacklogItemsByModule(ctx context.Context, moduleID *string) ([]BacklogItem, error) {
	rows, err := q.db.Query(ctx, listBacklogItemsByModule, moduleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BacklogItem{}
	for rows.Next() {
		var i BacklogItem
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.ModuleID,
			&i.Title,
			&i.Story,
			&i.AcceptanceCriteria,
			&i.Type,
			&i.Priority,
			&i.Readiness,
			&i.Estimate,
			&i.AiSuggestions,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBacklogItemsByProduct = `-- name: ListBacklogItemsByProduct :many
SELECT id, product_id, module_id, title, story, acceptance_criteria, type, priority, readiness, estimate, ai_suggestions, created_at, updated_at FROM backlog_items
WHERE product_id = $1
ORDER BY created_at DESC, id ASC
`

func (q *Queries) ListBacklogItemsByProduct(ctx context.Context, productID string) ([]BacklogItem, error) {
	rows, err := q.db.Query(ctx, listBacklogItemsByProduct, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BacklogItem{}
	for rows.Next() {
		var i BacklogItem
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.ModuleID,
			&i.Title,
			&i.Story,
			&i.AcceptanceCriteria,
			&i.Type,
			&i.Priority,
			&i.Readiness,
			&i.Estimate,
			&i.AiSuggestions,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSprintBacklogItems = `-- name: ListSprintBacklogItems :many
SELECT sbi.sprint_id,
       sbi.backlog_item_id,
       sbi.position,
       bi.product_id,
       bi.module_id,
       bi.title,
       bi.story,
       bi.acceptance_criteria,
       bi.type,
       bi.priority,
       bi.readiness,
       bi.estimate,
       bi.ai_suggestions
FROM sprint_backlog_items sbi
JOIN backlog_items bi ON bi.id = sbi.backlog_item_id
WHERE sbi.sprint_id = $1
ORDER BY sbi.position ASC, bi.title ASC
`

type ListSprintBacklogItemsRow struct {
	SprintID           string   `json:"sprintId"`
	BacklogItemID      string   `json:"backlogItemId"`
	Position           int32    `json:"position"`
	ProductID          string   `json:"productId"`
	ModuleID           *string  `json:"moduleId"`
	Title              string   `json:"title"`
	Story              string   `json:"story"`
	AcceptanceCriteria []string `json:"acceptanceCriteria"`
	Type               string   `json:"type"`
	Priority           string   `json:"priority"`
	Readiness          string   `json:"readiness"`
	Estimate           int32    `json:"estimate"`
	AiSuggestions      []string `json:"aiSuggestions"`
}

func (q *Queries) ListSprintBacklogItems(ctx context.Context, sprintID string) ([]ListSprintBacklogItemsRow, error) {
	rows, err := q.db.Query(ctx, listSprintBacklogItems, sprintID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSprintBacklogItemsRow{}
	for rows.Next() {
		var i ListSprintBacklogItemsRow
		if err := rows.Scan(
			&i.SprintID,
			&i.BacklogItemID,
			&i.Position,
			&i.ProductID,
			&i.ModuleID,
			&i.Title,
			&i.Story,
			&i.AcceptanceCriteria,
			&i.Type,
			&i.Priority,
			&i.Readiness,
			&i.Estimate,
			&i.AiSuggestions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSprintMembers = `-- name: ListSprintMembers :many
SELECT sm.sprint_id,
       sm.member_id,
       sm.allocation,
       sm.capacity_days,
       m.name  AS member_name,
       m.email AS member_email,
       m.role  AS member_role,
       m.role_label AS member_role_label
FROM sprint_members sm
JOIN members m ON m.id = sm.member_id
WHERE sm.sprint_id = $1
ORDER BY m.name ASC
`

type ListSprintMembersRow struct {
	SprintID        string  `json:"sprintId"`
	MemberID        string  `json:"memberId"`
	Allocation      int32   `json:"allocation"`
	CapacityDays    float64 `json:"capacityDays"`
	MemberName      string  `json:"memberName"`
	MemberEmail     string  `json:"memberEmail"`
	MemberRole      string  `json:"memberRole"`
	MemberRoleLabel string  `json:"memberRoleLabel"`
}

func (q *Queries) ListSprintMembers(ctx context.Context, sprintID string) ([]ListSprintMembersRow, error) {
	rows, err := q.db.Query(ctx, listSprintMembers, sprintID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSprintMembersRow{}
	for rows.Next() {
		var i ListSprintMembersRow
		if err := rows.Scan(
			&i.SprintID,
			&i.MemberID,
			&i.Allocation,
			&i.CapacityDays,
			&i.MemberName,
			&i.MemberEmail,
			&i.MemberRole,
			&i.MemberRoleLabel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSprintsByModule = `-- name: ListSprintsByModule :many
SELECT id, product_id, module_id, number, name, goal, start_date, end_date, working_days, days_left, status, committed, completed, progress, risk, created_at, updated_at FROM sprints
WHERE module_id = $1
ORDER BY number DESC
`

func (q *Queries) ListSprintsByModule(ctx context.Context, moduleID *string) ([]Sprint, error) {
	rows, err := q.db.Query(ctx, listSprintsByModule, moduleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Sprint{}
	for rows.Next() {
		var i Sprint
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.ModuleID,
			&i.Number,
			&i.Name,
			&i.Goal,
			&i.StartDate,
			&i.EndDate,
			&i.WorkingDays,
			&i.DaysLeft,
			&i.Status,
			&i.Committed,
			&i.Completed,
			&i.Progress,
			&i.Risk,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSprintsByProduct = `-- name: ListSprintsByProduct :many
SELECT id, product_id, module_id, number, name, goal, start_date, end_date, working_days, days_left, status, committed, completed, progress, risk, created_at, updated_at FROM sprints
WHERE product_id = $1
ORDER BY number DESC
`

func (q *Queries) ListSprintsByProduct(ctx context.Context, productID string) ([]Sprint, error) {
	rows, err := q.db.Query(ctx, listSprintsByProduct, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Sprint{}
	for rows.Next() {
		var i Sprint
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.ModuleID,
			&i.Number,
			&i.Name,
			&i.Goal,
			&i.StartDate,
			&i.EndDate,
			&i.WorkingDays,
			&i.DaysLeft,
			&i.Status,
			&i.Committed,
			&i.Completed,
			&i.Progress,
			&i.Risk,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextSprintNumber = `-- name: NextSprintNumber :one
SELECT COALESCE(MAX(number), 0) + 1 AS next_number
FROM sprints
WHERE product_id = $1
`

func (q *Queries) NextSprintNumber(ctx context.Context, productID string) (int32, error) {
	row := q.db.QueryRow(ctx, nextSprintNumber, productID)
	var next_number int32
	err := row.Scan(&next_number)
	return next_number, err
}

const removeSprintBacklogItem = `-- name: RemoveSprintBacklogItem :exec
DELETE FROM sprint_backlog_items
WHERE sprint_id = $1 AND backlog_item_id = $2
`

type RemoveSprintBacklogItemParams struct {
	SprintID      string `json:"sprintId"`
	BacklogItemID string `json:"backlogItemId"`
}

func (q *Queries) RemoveSprintBacklogItem(ctx context.Context, arg RemoveSprintBacklogItemParams) error {
	_, err := q.db.Exec(ctx, removeSprintBacklogItem, arg.SprintID, arg.BacklogItemID)
	return err
}

const removeSprintMember = `-- name: RemoveSprintMember :exec
DELETE FROM sprint_members
WHERE sprint_id = $1 AND member_id = $2
`

type RemoveSprintMemberParams struct {
	SprintID string `json:"sprintId"`
	MemberID string `json:"memberId"`
}

func (q *Queries) RemoveSprintMember(ctx context.Context, arg RemoveSprintMemberParams) error {
	_, err := q.db.Exec(ctx, removeSprintMember, arg.SprintID, arg.MemberID)
	return err
}

const updateBacklogItem = `-- name: UpdateBacklogItem :one
UPDATE backlog_items
SET module_id           = $2,
    title               = $3,
    story               = $4,
    acceptance_criteria = $5,
    type                = $6,
    priority            = $7,
    readiness           = $8,
    estimate            = $9,
    ai_suggestions      = $10,
    updated_at          = now()
WHERE id = $1
RETURNING id, product_id, module_id, title, story, acceptance_criteria, type, priority, readiness, estimate, ai_suggestions, created_at, updated_at
`

type UpdateBacklogItemParams struct {
	ID                 string   `json:"id"`
	ModuleID           *string  `json:"moduleId"`
	Title              string   `json:"title"`
	Story              string   `json:"story"`
	AcceptanceCriteria []string `json:"acceptanceCriteria"`
	Type               string   `json:"type"`
	Priority           string   `json:"priority"`
	Readiness          string   `json:"readiness"`
	Estimate           int32    `json:"estimate"`
	AiSuggestions      []string `json:"aiSuggestions"`
}

func (q *Queries) UpdateBacklogItem(ctx context.Context, arg UpdateBacklogItemParams) (BacklogItem, error) {
	row := q.db.QueryRow(ctx, updateBacklogItem,
		arg.ID,
		arg.ModuleID,
		arg.Title,
		arg.Story,
		arg.AcceptanceCriteria,
		arg.Type,
		arg.Priority,
		arg.Readiness,
		arg.Estimate,
		arg.AiSuggestions,
	)
	var i BacklogItem
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.ModuleID,
		&i.Title,
		&i.Story,
		&i.AcceptanceCriteria,
		&i.Type,
		&i.Priority,
		&i.Readiness,
		&i.Estimate,
		&i.AiSuggestions,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSprint = `-- name: UpdateSprint :one
UPDATE sprints
SET module_id    = $2,
    number       = $3,
    name         = $4,
    goal         = $5,
    start_date   = $6,
    end_date     = $7,
    working_days = $8,
    days_left    = $9,
    status       = $10,
    committed    = $11,
    completed    = $12,
    progress     = $13,
    risk         = $14,
    updated_at   = now()
WHERE id = $1
RETURNING id, product_id, module_id, number, name, goal, start_date, end_date, working_days, days_left, status, committed, completed, progress, risk, created_at, updated_at
`

type UpdateSprintParams struct {
	ID          string     `json:"id"`
	ModuleID    *string    `json:"moduleId"`
	Number      int32      `json:"number"`
	Name        string     `json:"name"`
	Goal        string     `json:"goal"`
	StartDate   *time.Time `json:"startDate"`
	EndDate     *time.Time `json:"endDate"`
	WorkingDays int32      `json:"workingDays"`
	DaysLeft    int32      `json:"daysLeft"`
	Status      string     `json:"status"`
	Committed   int32      `json:"committed"`
	Completed   int32      `json:"completed"`
	Progress    int32      `json:"progress"`
	Risk        string     `json:"risk"`
}

func (q *Queries) UpdateSprint(ctx context.Context, arg UpdateSprintParams) (Sprint, error) {
	row := q.db.QueryRow(ctx, updateSprint,
		arg.ID,
		arg.ModuleID,
		arg.Number,
		arg.Name,
		arg.Goal,
		arg.StartDate,
		arg.EndDate,
		arg.WorkingDays,
		arg.DaysLeft,
		arg.Status,
		arg.Committed,
		arg.Completed,
		arg.Progress,
		arg.Risk,
	)
	var i Sprint
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.ModuleID,
		&i.Number,
		&i.Name,
		&i.Goal,
		&i.StartDate,
		&i.EndDate,
		&i.WorkingDays,
		&i.DaysLeft,
		&i.Status,
		&i.Committed,
		&i.Completed,
		&i.Progress,
		&i.Risk,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
