// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sprints_backlog.sql

package db

import (
	"context"
	"time"
)

const addSprintBacklogItem = `-- name: AddSprintBacklogItem :one

INSERT INTO sprint_backlog_items (
    sprint_id,
    backlog_item_id,
    position
)
SELECT
    s.id,
    bi.id,
    $1
FROM sprints s
JOIN backlog_items bi
  ON bi.id = $2
 AND bi.product_id = s.product_id
WHERE s.id = $3
ON CONFLICT (sprint_id, backlog_item_id) DO UPDATE
SET position = EXCLUDED.position
RETURNING sprint_id, backlog_item_id, position
`

type AddSprintBacklogItemParams struct {
	Position      int32  `json:"position"`
	BacklogItemID string `json:"backlogItemId"`
	SprintID      string `json:"sprintId"`
}

// --------------------------------------------------- sprint_backlog_items ---
// The JOIN is the guard: an item may only be pulled into a sprint of its own
// product. A cross-product id matches no row, which the handler reports as a
// 400 — before, it linked happily and leaked the other product's story text.
// The position is chosen by the caller or computed under a row lock; see
// LockSprintForUpdate for why it cannot be computed inline.
func (q *Queries) AddSprintBacklogItem(ctx context.Context, arg AddSprintBacklogItemParams) (SprintBacklogItem, error) {
	row := q.db.QueryRow(ctx, addSprintBacklogItem, arg.Position, arg.BacklogItemID, arg.SprintID)
	var i SprintBacklogItem
	err := row.Scan(&i.SprintID, &i.BacklogItemID, &i.Position)
	return i, err
}

const addSprintMember = `-- name: AddSprintMember :one

INSERT INTO sprint_members (
    sprint_id,
    member_id,
    allocation,
    capacity_days
) VALUES (
    $1, $2, $3, $4
)
ON CONFLICT (sprint_id, member_id) DO UPDATE
SET allocation    = EXCLUDED.allocation,
    capacity_days = EXCLUDED.capacity_days
RETURNING sprint_id, member_id, allocation, capacity_days
`

type AddSprintMemberParams struct {
	SprintID     string  `json:"sprintId"`
	MemberID     string  `json:"memberId"`
	Allocation   int32   `json:"allocation"`
	CapacityDays float64 `json:"capacityDays"`
}

// --------------------------------------------------------- sprint_members ---
func (q *Queries) AddSprintMember(ctx context.Context, arg AddSprintMemberParams) (SprintMember, error) {
	row := q.db.QueryRow(ctx, addSprintMember,
		arg.SprintID,
		arg.MemberID,
		arg.Allocation,
		arg.CapacityDays,
	)
	var i SprintMember
	err := row.Scan(
		&i.SprintID,
		&i.MemberID,
		&i.Allocation,
		&i.CapacityDays,
	)
	return i, err
}

const createBacklogItem = `-- name: CreateBacklogItem :one

INSERT INTO backlog_items (
    id,
    product_id,
    module_id,
    title,
    story,
    acceptance_criteria,
    type,
    priority,
    readiness,
    estimate,
    ai_suggestions
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
RETURNING id, product_id, module_id, title, story, acceptance_criteria, type, priority, readiness, estimate, ai_suggestions, created_at, updated_at
`

type CreateBacklogItemParams struct {
	ID                 string   `json:"id"`
	ProductID          string   `json:"productId"`
	ModuleID           *string  `json:"moduleId"`
	Title              string   `json:"title"`
	Story              string   `json:"story"`
	AcceptanceCriteria []string `json:"acceptanceCriteria"`
	Type               string   `json:"type"`
	Priority           string   `json:"priority"`
	Readiness          string   `json:"readiness"`
	Estimate           int32    `json:"estimate"`
	AiSuggestions      []string `json:"aiSuggestions"`
}

// ---------------------------------------------------------- backlog_items ---
func (q *Queries) CreateBacklogItem(ctx context.Context, arg CreateBacklogItemParams) (BacklogItem, error) {
	row := q.db.QueryRow(ctx, createBacklogItem,
		arg.ID,
		arg.ProductID,
		arg.ModuleID,
		arg.Title,
		arg.Story,
		arg.AcceptanceCriteria,
		arg.Type,
		arg.Priority,
		arg.Readiness,
		arg.Estimate,
		arg.AiSuggestions,
	)
	var i BacklogItem
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.ModuleID,
		&i.Title,
		&i.Story,
		&i.AcceptanceCriteria,
		&i.Type,
		&i.Priority,
		&i.Readiness,
		&i.Estimate,
		&i.AiSuggestions,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSprint = `-- name: CreateSprint :one
INSERT INTO sprints (
    id,
    product_id,
    module_id,
    number,
    name,
    goal,
    start_date,
    end_date,
    working_days,
    days_left,
    status,
    committed,
    completed,
    progress,
    risk
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15
)
RETURNING id, product_id, module_id, number, name, goal, start_date, end_date, working_days, days_left, status, committed, completed, progress, risk, created_at, updated_at
`

type CreateSprintParams struct {
	ID          string     `json:"id"`
	ProductID   string     `json:"productId"`
	ModuleID    *string    `json:"moduleId"`
	Number      int32      `json:"number"`
	Name        string     `json:"name"`
	Goal        string     `json:"goal"`
	StartDate   *time.Time `json:"startDate"`
	EndDate     *time.Time `json:"endDate"`
	WorkingDays int32      `json:"workingDays"`
	DaysLeft    int32      `json:"daysLeft"`
	Status      string     `json:"status"`
	Committed   int32      `json:"committed"`
	Completed   int32      `json:"completed"`
	Progress    int32      `json:"progress"`
	Risk        string     `json:"risk"`
}

func (q *Queries) CreateSprint(ctx context.Context, arg CreateSprintParams) (Sprint, error) {
	row := q.db.QueryRow(ctx, createSprint,
		arg.ID,
		arg.ProductID,
		arg.ModuleID,
		arg.Number,
		arg.Name,
		arg.Goal,
		arg.StartDate,
		arg.EndDate,
		arg.WorkingDays,
		arg.DaysLeft,
		arg.Status,
		arg.Committed,
		arg.Completed,
		arg.Progress,
		arg.Risk,
	)
	var i Sprint
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.ModuleID,
		&i.Number,
		&i.Name,
		&i.Goal,
		&i.StartDate,
		&i.EndDate,
		&i.WorkingDays,
		&i.DaysLeft,
		&i.Status,
		&i.Committed,
		&i.Completed,
		&i.Progress,
		&i.Risk,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBacklogItem = `-- name: DeleteBacklogItem :exec
DELETE FROM backlog_items
WHERE id = $1
`

func (q *Queries) DeleteBacklogItem(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteBacklogItem, id)
	return err
}

const deleteSprint = `-- name: DeleteSprint :exec
DELETE FROM sprints
WHERE id = $1
`

func (q *Queries) DeleteSprint(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteSprint, id)
	return err
}

const getBacklogItem = `-- name: GetBacklogItem :one
SELECT id, product_id, module_id, title, story, acceptance_criteria, type, priority, readiness, estimate, ai_suggestions, created_at, updated_at FROM backlog_items
WHERE id = $1
`

func (q *Queries) GetBacklogItem(ctx context.Context, id string) (BacklogItem, error) {
	row := q.db.QueryRow(ctx, getBacklogItem, id)
	var i BacklogItem
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.ModuleID,
		&i.Title,
		&i.Story,
		&i.AcceptanceCriteria,
		&i.Type,
		&i.Priority,
		&i.Readiness,
		&i.Estimate,
		&i.AiSuggestions,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSprint = `-- name: GetSprint :one
SELECT id, product_id, module_id, number, name, goal, start_date, end_date, working_days, days_left, status, committed, completed, progress, risk, created_at, updated_at FROM sprints
WHERE id = $1
`

func (q *Queries) GetSprint(ctx context.Context, id string) (Sprint, error) {
	row := q.db.QueryRow(ctx, getSprint, id)
	var i Sprint
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.ModuleID,
		&i.Number,
		&i.Name,
		&i.Goal,
		&i.StartDate,
		&i.EndDate,
		&i.WorkingDays,
		&i.DaysLeft,
		&i.Status,
		&i.Committed,
		&i.Completed,
		&i.Progress,
		&i.Risk,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBacklogItemsByModule = `-- name: ListBacklogItemsByModule :many
SELECT id, product_id, module_id, title, story, acceptance_criteria, type, priority, readiness, estimate, ai_suggestions, created_at, updated_at FROM backlog_items
WHERE module_id = $1
ORDER BY created_at DESC, id ASC
LIMIT $3 OFFSET $2
`

type ListBacklogItemsByModuleParams struct {
	ModuleID *string `json:"moduleId"`
	Off      int32   `json:"off"`
	Lim      int32   `json:"lim"`
}

func (q *Queries) ListBacklogItemsByModule(ctx context.Context, arg ListBacklogItemsByModuleParams) ([]BacklogItem, error) {
	rows, err := q.db.Query(ctx, listBacklogItemsByModule, arg.ModuleID, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BacklogItem{}
	for rows.Next() {
		var i BacklogItem
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.ModuleID,
			&i.Title,
			&i.Story,
			&i.AcceptanceCriteria,
			&i.Type,
			&i.Priority,
			&i.Readiness,
			&i.Estimate,
			&i.AiSuggestions,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBacklogItemsByProduct = `-- name: ListBacklogItemsByProduct :many
SELECT id, product_id, module_id, title, story, acceptance_criteria, type, priority, readiness, estimate, ai_suggestions, created_at, updated_at FROM backlog_items
WHERE product_id = $1
ORDER BY created_at DESC, id ASC
LIMIT $3 OFFSET $2
`

type ListBacklogItemsByProductParams struct {
	ProductID string `json:"productId"`
	Off       int32  `json:"off"`
	Lim       int32  `json:"lim"`
}

func (q *Queries) ListBacklogItemsByProduct(ctx context.Context, arg ListBacklogItemsByProductParams) ([]BacklogItem, error) {
	rows, err := q.db.Query(ctx, listBacklogItemsByProduct, arg.ProductID, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BacklogItem{}
	for rows.Next() {
		var i BacklogItem
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.ModuleID,
			&i.Title,
			&i.Story,
			&i.AcceptanceCriteria,
			&i.Type,
			&i.Priority,
			&i.Readiness,
			&i.Estimate,
			&i.AiSuggestions,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSprintBacklogItems = `-- name: ListSprintBacklogItems :many
SELECT sbi.sprint_id,
       sbi.backlog_item_id,
       sbi.position,
       bi.product_id,
       bi.module_id,
       bi.title,
       bi.story,
       bi.acceptance_criteria,
       bi.type,
       bi.priority,
       bi.readiness,
       bi.estimate,
       bi.ai_suggestions
FROM sprint_backlog_items sbi
JOIN backlog_items bi ON bi.id = sbi.backlog_item_id
WHERE sbi.sprint_id = $1
ORDER BY sbi.position ASC, bi.title ASC, bi.id ASC
`

type ListSprintBacklogItemsRow struct {
	SprintID           string   `json:"sprintId"`
	BacklogItemID      string   `json:"backlogItemId"`
	Position           int32    `json:"position"`
	ProductID          string   `json:"productId"`
	ModuleID           *string  `json:"moduleId"`
	Title              string   `json:"title"`
	Story              string   `json:"story"`
	AcceptanceCriteria []string `json:"acceptanceCriteria"`
	Type               string   `json:"type"`
	Priority           string   `json:"priority"`
	Readiness          string   `json:"readiness"`
	Estimate           int32    `json:"estimate"`
	AiSuggestions      []string `json:"aiSuggestions"`
}

func (q *Queries) ListSprintBacklogItems(ctx context.Context, sprintID string) ([]ListSprintBacklogItemsRow, error) {
	rows, err := q.db.Query(ctx, listSprintBacklogItems, sprintID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSprintBacklogItemsRow{}
	for rows.Next() {
		var i ListSprintBacklogItemsRow
		if err := rows.Scan(
			&i.SprintID,
			&i.BacklogItemID,
			&i.Position,
			&i.ProductID,
			&i.ModuleID,
			&i.Title,
			&i.Story,
			&i.AcceptanceCriteria,
			&i.Type,
			&i.Priority,
			&i.Readiness,
			&i.Estimate,
			&i.AiSuggestions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSprintMembers = `-- name: ListSprintMembers :many
SELECT sm.sprint_id,
       sm.member_id,
       sm.allocation,
       sm.capacity_days,
       m.name  AS member_name,
       m.email AS member_email,
       m.role  AS member_role,
       m.role_label AS member_role_label
FROM sprint_members sm
JOIN members m ON m.id = sm.member_id
WHERE sm.sprint_id = $1
ORDER BY m.name ASC, m.id ASC
`

type ListSprintMembersRow struct {
	SprintID        string  `json:"sprintId"`
	MemberID        string  `json:"memberId"`
	Allocation      int32   `json:"allocation"`
	CapacityDays    float64 `json:"capacityDays"`
	MemberName      string  `json:"memberName"`
	MemberEmail     string  `json:"memberEmail"`
	MemberRole      string  `json:"memberRole"`
	MemberRoleLabel string  `json:"memberRoleLabel"`
}

func (q *Queries) ListSprintMembers(ctx context.Context, sprintID string) ([]ListSprintMembersRow, error) {
	rows, err := q.db.Query(ctx, listSprintMembers, sprintID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSprintMembersRow{}
	for rows.Next() {
		var i ListSprintMembersRow
		if err := rows.Scan(
			&i.SprintID,
			&i.MemberID,
			&i.Allocation,
			&i.CapacityDays,
			&i.MemberName,
			&i.MemberEmail,
			&i.MemberRole,
			&i.MemberRoleLabel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSprintsByModule = `-- name: ListSprintsByModule :many
SELECT id, product_id, module_id, number, name, goal, start_date, end_date, working_days, days_left, status, committed, completed, progress, risk, created_at, updated_at FROM sprints
WHERE module_id = $1
ORDER BY number DESC, id
LIMIT $3 OFFSET $2
`

type ListSprintsByModuleParams struct {
	ModuleID *string `json:"moduleId"`
	Off      int32   `json:"off"`
	Lim      int32   `json:"lim"`
}

// number is only unique per product, so it cannot order a cross-product list
// on its own.
func (q *Queries) ListSprintsByModule(ctx context.Context, arg ListSprintsByModuleParams) ([]Sprint, error) {
	rows, err := q.db.Query(ctx, listSprintsByModule, arg.ModuleID, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Sprint{}
	for rows.Next() {
		var i Sprint
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.ModuleID,
			&i.Number,
			&i.Name,
			&i.Goal,
			&i.StartDate,
			&i.EndDate,
			&i.WorkingDays,
			&i.DaysLeft,
			&i.Status,
			&i.Committed,
			&i.Completed,
			&i.Progress,
			&i.Risk,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSprintsByProduct = `-- name: ListSprintsByProduct :many
SELECT id, product_id, module_id, number, name, goal, start_date, end_date, working_days, days_left, status, committed, completed, progress, risk, created_at, updated_at FROM sprints
WHERE product_id = $1
ORDER BY number DESC, id
LIMIT $3 OFFSET $2
`

type ListSprintsByProductParams struct {
	ProductID string `json:"productId"`
	Off       int32  `json:"off"`
	Lim       int32  `json:"lim"`
}

func (q *Queries) ListSprintsByProduct(ctx context.Context, arg ListSprintsByProductParams) ([]Sprint, error) {
	rows, err := q.db.Query(ctx, listSprintsByProduct, arg.ProductID, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Sprint{}
	for rows.Next() {
		var i Sprint
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.ModuleID,
			&i.Number,
			&i.Name,
			&i.Goal,
			&i.StartDate,
			&i.EndDate,
			&i.WorkingDays,
			&i.DaysLeft,
			&i.Status,
			&i.Committed,
			&i.Completed,
			&i.Progress,
			&i.Risk,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockBacklogItemForShare = `-- name: LockBacklogItemForShare :one
SELECT id FROM backlog_items
WHERE id = $1
FOR KEY SHARE
`

// Taken before the sprint lock so the ordering matches the cascade's:
// DELETE FROM products reaches backlog_items before sprints, so locking the
// sprint first and the item second is an AB-BA cycle that deadlocks every
// concurrent parent delete.
func (q *Queries) LockBacklogItemForShare(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, lockBacklogItemForShare, id)
	var id_2 string
	err := row.Scan(&id_2)
	return id_2, err
}

const lockProductForUpdate = `-- name: LockProductForUpdate :one


SELECT id FROM products
WHERE id = $1
FOR NO KEY UPDATE
`

// Sprints, sprint membership, sprint backlog and the product backlog.
// Naming note: products = UI "Module", modules = UI "Component".
// ---------------------------------------------------------------- sprints ---
// Serialises per-product sequencing (sprint numbers, component positions).
// A single statement cannot do this for itself: under READ COMMITTED its
// snapshot is fixed before any lock it takes, so concurrent statements all
// read the same MAX() no matter how they queue. Taking the row lock in its own
// statement, inside a transaction, is what makes the next read see the truth.
//
// FOR NO KEY UPDATE, not FOR UPDATE: only the latter conflicts with the
// FOR KEY SHARE that every child insert's foreign-key check takes, which would
// freeze unrelated endpoints (backlog, decisions, explicitly-numbered sprints)
// for as long as one sequencing transaction runs.
func (q *Queries) LockProductForUpdate(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, lockProductForUpdate, id)
	var id_2 string
	err := row.Scan(&id_2)
	return id_2, err
}

const lockSprintForUpdate = `-- name: LockSprintForUpdate :one
SELECT id FROM sprints
WHERE id = $1
FOR NO KEY UPDATE
`

func (q *Queries) LockSprintForUpdate(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, lockSprintForUpdate, id)
	var id_2 string
	err := row.Scan(&id_2)
	return id_2, err
}

const nextSprintBacklogPosition = `-- name: NextSprintBacklogPosition :one
SELECT COALESCE(MAX(position), -1) + 1 AS next_position
FROM sprint_backlog_items
WHERE sprint_id = $1
`

func (q *Queries) NextSprintBacklogPosition(ctx context.Context, sprintID string) (int32, error) {
	row := q.db.QueryRow(ctx, nextSprintBacklogPosition, sprintID)
	var next_position int32
	err := row.Scan(&next_position)
	return next_position, err
}

const nextSprintNumber = `-- name: NextSprintNumber :one
SELECT COALESCE(MAX(number), 0) + 1 AS next_number
FROM sprints
WHERE product_id = $1
`

func (q *Queries) NextSprintNumber(ctx context.Context, productID string) (int32, error) {
	row := q.db.QueryRow(ctx, nextSprintNumber, productID)
	var next_number int32
	err := row.Scan(&next_number)
	return next_number, err
}

const removeSprintBacklogItem = `-- name: RemoveSprintBacklogItem :exec
DELETE FROM sprint_backlog_items
WHERE sprint_id = $1 AND backlog_item_id = $2
`

type RemoveSprintBacklogItemParams struct {
	SprintID      string `json:"sprintId"`
	BacklogItemID string `json:"backlogItemId"`
}

func (q *Queries) RemoveSprintBacklogItem(ctx context.Context, arg RemoveSprintBacklogItemParams) error {
	_, err := q.db.Exec(ctx, removeSprintBacklogItem, arg.SprintID, arg.BacklogItemID)
	return err
}

const removeSprintMember = `-- name: RemoveSprintMember :exec
DELETE FROM sprint_members
WHERE sprint_id = $1 AND member_id = $2
`

type RemoveSprintMemberParams struct {
	SprintID string `json:"sprintId"`
	MemberID string `json:"memberId"`
}

func (q *Queries) RemoveSprintMember(ctx context.Context, arg RemoveSprintMemberParams) error {
	_, err := q.db.Exec(ctx, removeSprintMember, arg.SprintID, arg.MemberID)
	return err
}

const updateBacklogItem = `-- name: UpdateBacklogItem :one
UPDATE backlog_items
SET module_id           = COALESCE($1, module_id),
    title               = COALESCE($2, title),
    story               = COALESCE($3, story),
    acceptance_criteria = COALESCE($4::text[], acceptance_criteria),
    type                = COALESCE($5, type),
    priority            = COALESCE($6, priority),
    readiness           = COALESCE($7, readiness),
    estimate            = COALESCE($8, estimate),
    ai_suggestions      = COALESCE($9::text[], ai_suggestions),
    updated_at          = now()
WHERE id = $10
RETURNING id, product_id, module_id, title, story, acceptance_criteria, type, priority, readiness, estimate, ai_suggestions, created_at, updated_at
`

type UpdateBacklogItemParams struct {
	ModuleID           *string  `json:"moduleId"`
	Title              *string  `json:"title"`
	Story              *string  `json:"story"`
	AcceptanceCriteria []string `json:"acceptanceCriteria"`
	Type               *string  `json:"type"`
	Priority           *string  `json:"priority"`
	Readiness          *string  `json:"readiness"`
	Estimate           *int32   `json:"estimate"`
	AiSuggestions      []string `json:"aiSuggestions"`
	ID                 string   `json:"id"`
}

// Partial update (see UpdateClient).
func (q *Queries) UpdateBacklogItem(ctx context.Context, arg UpdateBacklogItemParams) (BacklogItem, error) {
	row := q.db.QueryRow(ctx, updateBacklogItem,
		arg.ModuleID,
		arg.Title,
		arg.Story,
		arg.AcceptanceCriteria,
		arg.Type,
		arg.Priority,
		arg.Readiness,
		arg.Estimate,
		arg.AiSuggestions,
		arg.ID,
	)
	var i BacklogItem
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.ModuleID,
		&i.Title,
		&i.Story,
		&i.AcceptanceCriteria,
		&i.Type,
		&i.Priority,
		&i.Readiness,
		&i.Estimate,
		&i.AiSuggestions,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSprint = `-- name: UpdateSprint :one
UPDATE sprints
SET module_id    = COALESCE($1, module_id),
    number       = COALESCE($2, number),
    name         = COALESCE($3, name),
    goal         = COALESCE($4, goal),
    start_date   = COALESCE($5, start_date),
    end_date     = COALESCE($6, end_date),
    working_days = COALESCE($7, working_days),
    days_left    = COALESCE($8, days_left),
    status       = COALESCE($9, status),
    committed    = COALESCE($10, committed),
    completed    = COALESCE($11, completed),
    progress     = COALESCE($12, progress),
    risk         = COALESCE($13, risk),
    updated_at   = now()
WHERE id = $14
RETURNING id, product_id, module_id, number, name, goal, start_date, end_date, working_days, days_left, status, committed, completed, progress, risk, created_at, updated_at
`

type UpdateSprintParams struct {
	ModuleID    *string    `json:"moduleId"`
	Number      *int32     `json:"number"`
	Name        *string    `json:"name"`
	Goal        *string    `json:"goal"`
	StartDate   *time.Time `json:"startDate"`
	EndDate     *time.Time `json:"endDate"`
	WorkingDays *int32     `json:"workingDays"`
	DaysLeft    *int32     `json:"daysLeft"`
	Status      *string    `json:"status"`
	Committed   *int32     `json:"committed"`
	Completed   *int32     `json:"completed"`
	Progress    *int32     `json:"progress"`
	Risk        *string    `json:"risk"`
	ID          string     `json:"id"`
}

// Partial update (see UpdateClient).
func (q *Queries) UpdateSprint(ctx context.Context, arg UpdateSprintParams) (Sprint, error) {
	row := q.db.QueryRow(ctx, updateSprint,
		arg.ModuleID,
		arg.Number,
		arg.Name,
		arg.Goal,
		arg.StartDate,
		arg.EndDate,
		arg.WorkingDays,
		arg.DaysLeft,
		arg.Status,
		arg.Committed,
		arg.Completed,
		arg.Progress,
		arg.Risk,
		arg.ID,
	)
	var i Sprint
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.ModuleID,
		&i.Number,
		&i.Name,
		&i.Goal,
		&i.StartDate,
		&i.EndDate,
		&i.WorkingDays,
		&i.DaysLeft,
		&i.Status,
		&i.Committed,
		&i.Completed,
		&i.Progress,
		&i.Risk,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
