// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tasks_members_support.sql

package db

import (
	"context"
	"time"
)

const addMasterValue = `-- name: AddMasterValue :one
INSERT INTO master_lists (key, value, position)
VALUES ($1, $2, $3)
ON CONFLICT (key, value) DO UPDATE
SET position = EXCLUDED.position
RETURNING key, value, position
`

type AddMasterValueParams struct {
	Key      string `json:"key"`
	Value    string `json:"value"`
	Position int32  `json:"position"`
}

func (q *Queries) AddMasterValue(ctx context.Context, arg AddMasterValueParams) (MasterList, error) {
	row := q.db.QueryRow(ctx, addMasterValue, arg.Key, arg.Value, arg.Position)
	var i MasterList
	err := row.Scan(&i.Key, &i.Value, &i.Position)
	return i, err
}

const createDecision = `-- name: CreateDecision :one

INSERT INTO decisions (
    id,
    product_id,
    decided_on,
    title,
    detail,
    owner,
    status
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, product_id, decided_on, title, detail, owner, status, created_at, updated_at
`

type CreateDecisionParams struct {
	ID        string    `json:"id"`
	ProductID string    `json:"productId"`
	DecidedOn time.Time `json:"decidedOn"`
	Title     string    `json:"title"`
	Detail    string    `json:"detail"`
	Owner     string    `json:"owner"`
	Status    string    `json:"status"`
}

// -------------------------------------------------------------- decisions ---
func (q *Queries) CreateDecision(ctx context.Context, arg CreateDecisionParams) (Decision, error) {
	row := q.db.QueryRow(ctx, createDecision,
		arg.ID,
		arg.ProductID,
		arg.DecidedOn,
		arg.Title,
		arg.Detail,
		arg.Owner,
		arg.Status,
	)
	var i Decision
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.DecidedOn,
		&i.Title,
		&i.Detail,
		&i.Owner,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createGeneratedReport = `-- name: CreateGeneratedReport :one

INSERT INTO generated_reports (
    id,
    product_id,
    sprint_id,
    type,
    template,
    period,
    generated_on,
    status
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, product_id, sprint_id, type, template, period, generated_on, status, created_at, updated_at
`

type CreateGeneratedReportParams struct {
	ID          string    `json:"id"`
	ProductID   string    `json:"productId"`
	SprintID    *string   `json:"sprintId"`
	Type        string    `json:"type"`
	Template    string    `json:"template"`
	Period      string    `json:"period"`
	GeneratedOn time.Time `json:"generatedOn"`
	Status      string    `json:"status"`
}

// ------------------------------------------------------ generated_reports ---
func (q *Queries) CreateGeneratedReport(ctx context.Context, arg CreateGeneratedReportParams) (GeneratedReport, error) {
	row := q.db.QueryRow(ctx, createGeneratedReport,
		arg.ID,
		arg.ProductID,
		arg.SprintID,
		arg.Type,
		arg.Template,
		arg.Period,
		arg.GeneratedOn,
		arg.Status,
	)
	var i GeneratedReport
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.SprintID,
		&i.Type,
		&i.Template,
		&i.Period,
		&i.GeneratedOn,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createMember = `-- name: CreateMember :one

INSERT INTO members (
    id,
    name,
    email,
    role,
    role_label,
    skill_tags,
    allocation,
    capacity_days,
    workload,
    status
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
RETURNING id, name, email, role, role_label, skill_tags, allocation, capacity_days, workload, status, created_at, updated_at
`

type CreateMemberParams struct {
	ID           string   `json:"id"`
	Name         string   `json:"name"`
	Email        string   `json:"email"`
	Role         string   `json:"role"`
	RoleLabel    string   `json:"roleLabel"`
	SkillTags    []string `json:"skillTags"`
	Allocation   int32    `json:"allocation"`
	CapacityDays float64  `json:"capacityDays"`
	Workload     int32    `json:"workload"`
	Status       string   `json:"status"`
}

// ---------------------------------------------------------------- members ---
func (q *Queries) CreateMember(ctx context.Context, arg CreateMemberParams) (Member, error) {
	row := q.db.QueryRow(ctx, createMember,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.Role,
		arg.RoleLabel,
		arg.SkillTags,
		arg.Allocation,
		arg.CapacityDays,
		arg.Workload,
		arg.Status,
	)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Role,
		&i.RoleLabel,
		&i.SkillTags,
		&i.Allocation,
		&i.CapacityDays,
		&i.Workload,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createReportQueueItem = `-- name: CreateReportQueueItem :one
INSERT INTO report_queue (
    id,
    title,
    product_id,
    client,
    type,
    template,
    due,
    status
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, title, product_id, client, type, template, due, status, created_at, updated_at
`

type CreateReportQueueItemParams struct {
	ID        string     `json:"id"`
	Title     string     `json:"title"`
	ProductID string     `json:"productId"`
	Client    string     `json:"client"`
	Type      string     `json:"type"`
	Template  string     `json:"template"`
	Due       *time.Time `json:"due"`
	Status    string     `json:"status"`
}

func (q *Queries) CreateReportQueueItem(ctx context.Context, arg CreateReportQueueItemParams) (ReportQueue, error) {
	row := q.db.QueryRow(ctx, createReportQueueItem,
		arg.ID,
		arg.Title,
		arg.ProductID,
		arg.Client,
		arg.Type,
		arg.Template,
		arg.Due,
		arg.Status,
	)
	var i ReportQueue
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.ProductID,
		&i.Client,
		&i.Type,
		&i.Template,
		&i.Due,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTask = `-- name: CreateTask :one

INSERT INTO tasks (
    id,
    sprint_id,
    backlog_item_id,
    title,
    module_name,
    assignee_id,
    estimate,
    board_column,
    priority,
    blocked_reason,
    blocked_days,
    off_goal
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
)
RETURNING id, sprint_id, backlog_item_id, title, module_name, assignee_id, estimate, board_column, priority, blocked_reason, blocked_days, off_goal, created_at, updated_at
`

type CreateTaskParams struct {
	ID            string  `json:"id"`
	SprintID      string  `json:"sprintId"`
	BacklogItemID string  `json:"backlogItemId"`
	Title         string  `json:"title"`
	ModuleName    string  `json:"moduleName"`
	AssigneeID    *string `json:"assigneeId"`
	Estimate      int32   `json:"estimate"`
	BoardColumn   string  `json:"boardColumn"`
	Priority      string  `json:"priority"`
	BlockedReason *string `json:"blockedReason"`
	BlockedDays   *int32  `json:"blockedDays"`
	OffGoal       bool    `json:"offGoal"`
}

// ------------------------------------------------------------------ tasks ---
func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.ID,
		arg.SprintID,
		arg.BacklogItemID,
		arg.Title,
		arg.ModuleName,
		arg.AssigneeID,
		arg.Estimate,
		arg.BoardColumn,
		arg.Priority,
		arg.BlockedReason,
		arg.BlockedDays,
		arg.OffGoal,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.SprintID,
		&i.BacklogItemID,
		&i.Title,
		&i.ModuleName,
		&i.AssigneeID,
		&i.Estimate,
		&i.BoardColumn,
		&i.Priority,
		&i.BlockedReason,
		&i.BlockedDays,
		&i.OffGoal,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDecision = `-- name: DeleteDecision :exec
DELETE FROM decisions
WHERE id = $1
`

func (q *Queries) DeleteDecision(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteDecision, id)
	return err
}

const deleteMasterValue = `-- name: DeleteMasterValue :exec
DELETE FROM master_lists
WHERE key = $1 AND value = $2
`

type DeleteMasterValueParams struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

func (q *Queries) DeleteMasterValue(ctx context.Context, arg DeleteMasterValueParams) error {
	_, err := q.db.Exec(ctx, deleteMasterValue, arg.Key, arg.Value)
	return err
}

const deleteMember = `-- name: DeleteMember :exec
DELETE FROM members
WHERE id = $1
`

func (q *Queries) DeleteMember(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteMember, id)
	return err
}

const deleteReportQueueItem = `-- name: DeleteReportQueueItem :exec
DELETE FROM report_queue
WHERE id = $1
`

func (q *Queries) DeleteReportQueueItem(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteReportQueueItem, id)
	return err
}

const deleteReportTemplate = `-- name: DeleteReportTemplate :exec
DELETE FROM report_templates
WHERE id = $1
`

func (q *Queries) DeleteReportTemplate(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteReportTemplate, id)
	return err
}

const deleteTask = `-- name: DeleteTask :exec
DELETE FROM tasks
WHERE id = $1
`

func (q *Queries) DeleteTask(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteTask, id)
	return err
}

const deleteTaskDod = `-- name: DeleteTaskDod :exec
DELETE FROM task_dod
WHERE task_id = $1
`

func (q *Queries) DeleteTaskDod(ctx context.Context, taskID string) error {
	_, err := q.db.Exec(ctx, deleteTaskDod, taskID)
	return err
}

const getDecision = `-- name: GetDecision :one
SELECT id, product_id, decided_on, title, detail, owner, status, created_at, updated_at FROM decisions
WHERE id = $1
`

func (q *Queries) GetDecision(ctx context.Context, id string) (Decision, error) {
	row := q.db.QueryRow(ctx, getDecision, id)
	var i Decision
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.DecidedOn,
		&i.Title,
		&i.Detail,
		&i.Owner,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMember = `-- name: GetMember :one
SELECT id, name, email, role, role_label, skill_tags, allocation, capacity_days, workload, status, created_at, updated_at FROM members
WHERE id = $1
`

func (q *Queries) GetMember(ctx context.Context, id string) (Member, error) {
	row := q.db.QueryRow(ctx, getMember, id)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Role,
		&i.RoleLabel,
		&i.SkillTags,
		&i.Allocation,
		&i.CapacityDays,
		&i.Workload,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTask = `-- name: GetTask :one
SELECT id, sprint_id, backlog_item_id, title, module_name, assignee_id, estimate, board_column, priority, blocked_reason, blocked_days, off_goal, created_at, updated_at FROM tasks
WHERE id = $1
`

func (q *Queries) GetTask(ctx context.Context, id string) (Task, error) {
	row := q.db.QueryRow(ctx, getTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.SprintID,
		&i.BacklogItemID,
		&i.Title,
		&i.ModuleName,
		&i.AssigneeID,
		&i.Estimate,
		&i.BoardColumn,
		&i.Priority,
		&i.BlockedReason,
		&i.BlockedDays,
		&i.OffGoal,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkspaceSettings = `-- name: GetWorkspaceSettings :one

SELECT id, name, settings, dod_template, updated_at FROM workspace_settings
WHERE id = TRUE
`

// ------------------------------------------------------ workspace_settings --
func (q *Queries) GetWorkspaceSettings(ctx context.Context) (WorkspaceSetting, error) {
	row := q.db.QueryRow(ctx, getWorkspaceSettings)
	var i WorkspaceSetting
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Settings,
		&i.DodTemplate,
		&i.UpdatedAt,
	)
	return i, err
}

const listDecisionsByProduct = `-- name: ListDecisionsByProduct :many
SELECT id, product_id, decided_on, title, detail, owner, status, created_at, updated_at FROM decisions
WHERE product_id = $1
ORDER BY decided_on DESC, id
`

func (q *Queries) ListDecisionsByProduct(ctx context.Context, productID string) ([]Decision, error) {
	rows, err := q.db.Query(ctx, listDecisionsByProduct, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Decision{}
	for rows.Next() {
		var i Decision
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.DecidedOn,
			&i.Title,
			&i.Detail,
			&i.Owner,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGeneratedReportsByProduct = `-- name: ListGeneratedReportsByProduct :many
SELECT id, product_id, sprint_id, type, template, period, generated_on, status, created_at, updated_at FROM generated_reports
WHERE product_id = $1
ORDER BY generated_on DESC, id
`

func (q *Queries) ListGeneratedReportsByProduct(ctx context.Context, productID string) ([]GeneratedReport, error) {
	rows, err := q.db.Query(ctx, listGeneratedReportsByProduct, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GeneratedReport{}
	for rows.Next() {
		var i GeneratedReport
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.SprintID,
			&i.Type,
			&i.Template,
			&i.Period,
			&i.GeneratedOn,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMasterValues = `-- name: ListMasterValues :many

SELECT key, value, position FROM master_lists
WHERE key = $1
ORDER BY position, value
`

// ----------------------------------------------------------- master_lists ---
func (q *Queries) ListMasterValues(ctx context.Context, key string) ([]MasterList, error) {
	rows, err := q.db.Query(ctx, listMasterValues, key)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MasterList{}
	for rows.Next() {
		var i MasterList
		if err := rows.Scan(&i.Key, &i.Value, &i.Position); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembers = `-- name: ListMembers :many
SELECT id, name, email, role, role_label, skill_tags, allocation, capacity_days, workload, status, created_at, updated_at FROM members
ORDER BY name, id
`

func (q *Queries) ListMembers(ctx context.Context) ([]Member, error) {
	rows, err := q.db.Query(ctx, listMembers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Member{}
	for rows.Next() {
		var i Member
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Role,
			&i.RoleLabel,
			&i.SkillTags,
			&i.Allocation,
			&i.CapacityDays,
			&i.Workload,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReportQueue = `-- name: ListReportQueue :many

SELECT id, title, product_id, client, type, template, due, status, created_at, updated_at FROM report_queue
ORDER BY due NULLS LAST, id
`

// ----------------------------------------------------------- report_queue ---
func (q *Queries) ListReportQueue(ctx context.Context) ([]ReportQueue, error) {
	rows, err := q.db.Query(ctx, listReportQueue)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReportQueue{}
	for rows.Next() {
		var i ReportQueue
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.ProductID,
			&i.Client,
			&i.Type,
			&i.Template,
			&i.Due,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReportTemplates = `-- name: ListReportTemplates :many

SELECT id, name, audience, visibility, sections, created_at, updated_at FROM report_templates
ORDER BY name
`

// ------------------------------------------------------- report_templates ---
func (q *Queries) ListReportTemplates(ctx context.Context) ([]ReportTemplate, error) {
	rows, err := q.db.Query(ctx, listReportTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReportTemplate{}
	for rows.Next() {
		var i ReportTemplate
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Audience,
			&i.Visibility,
			&i.Sections,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoles = `-- name: ListRoles :many

SELECT id, label, permissions FROM roles
ORDER BY label, id
`

// ------------------------------------------------------------------ roles ---
func (q *Queries) ListRoles(ctx context.Context) ([]Role, error) {
	rows, err := q.db.Query(ctx, listRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Role{}
	for rows.Next() {
		var i Role
		if err := rows.Scan(&i.ID, &i.Label, &i.Permissions); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskDod = `-- name: ListTaskDod :many
SELECT task_id, position, label, done FROM task_dod
WHERE task_id = $1
ORDER BY position
`

func (q *Queries) ListTaskDod(ctx context.Context, taskID string) ([]TaskDod, error) {
	rows, err := q.db.Query(ctx, listTaskDod, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskDod{}
	for rows.Next() {
		var i TaskDod
		if err := rows.Scan(
			&i.TaskID,
			&i.Position,
			&i.Label,
			&i.Done,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByBacklogItem = `-- name: ListTasksByBacklogItem :many
SELECT id, sprint_id, backlog_item_id, title, module_name, assignee_id, estimate, board_column, priority, blocked_reason, blocked_days, off_goal, created_at, updated_at FROM tasks
WHERE backlog_item_id = $1
ORDER BY created_at, id
`

func (q *Queries) ListTasksByBacklogItem(ctx context.Context, backlogItemID string) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasksByBacklogItem, backlogItemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.SprintID,
			&i.BacklogItemID,
			&i.Title,
			&i.ModuleName,
			&i.AssigneeID,
			&i.Estimate,
			&i.BoardColumn,
			&i.Priority,
			&i.BlockedReason,
			&i.BlockedDays,
			&i.OffGoal,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksBySprint = `-- name: ListTasksBySprint :many
SELECT id, sprint_id, backlog_item_id, title, module_name, assignee_id, estimate, board_column, priority, blocked_reason, blocked_days, off_goal, created_at, updated_at FROM tasks
WHERE sprint_id = $1
ORDER BY created_at, id
`

func (q *Queries) ListTasksBySprint(ctx context.Context, sprintID string) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasksBySprint, sprintID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.SprintID,
			&i.BacklogItemID,
			&i.Title,
			&i.ModuleName,
			&i.AssigneeID,
			&i.Estimate,
			&i.BoardColumn,
			&i.Priority,
			&i.BlockedReason,
			&i.BlockedDays,
			&i.OffGoal,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markGeneratedReportSent = `-- name: MarkGeneratedReportSent :one
UPDATE generated_reports
SET status     = 'sent',
    updated_at = now()
WHERE id = $1
RETURNING id, product_id, sprint_id, type, template, period, generated_on, status, created_at, updated_at
`

func (q *Queries) MarkGeneratedReportSent(ctx context.Context, id string) (GeneratedReport, error) {
	row := q.db.QueryRow(ctx, markGeneratedReportSent, id)
	var i GeneratedReport
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.SprintID,
		&i.Type,
		&i.Template,
		&i.Period,
		&i.GeneratedOn,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const moveTask = `-- name: MoveTask :one
UPDATE tasks
SET board_column = $2,
    updated_at   = now()
WHERE id = $1
RETURNING id, sprint_id, backlog_item_id, title, module_name, assignee_id, estimate, board_column, priority, blocked_reason, blocked_days, off_goal, created_at, updated_at
`

type MoveTaskParams struct {
	ID          string `json:"id"`
	BoardColumn string `json:"boardColumn"`
}

func (q *Queries) MoveTask(ctx context.Context, arg MoveTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, moveTask, arg.ID, arg.BoardColumn)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.SprintID,
		&i.BacklogItemID,
		&i.Title,
		&i.ModuleName,
		&i.AssigneeID,
		&i.Estimate,
		&i.BoardColumn,
		&i.Priority,
		&i.BlockedReason,
		&i.BlockedDays,
		&i.OffGoal,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setTaskDodItem = `-- name: SetTaskDodItem :one

INSERT INTO task_dod (task_id, position, label, done)
VALUES ($1, $2, $3, $4)
ON CONFLICT (task_id, position) DO UPDATE
SET label = EXCLUDED.label,
    done  = EXCLUDED.done
RETURNING task_id, position, label, done
`

type SetTaskDodItemParams struct {
	TaskID   string `json:"taskId"`
	Position int32  `json:"position"`
	Label    string `json:"label"`
	Done     bool   `json:"done"`
}

// --------------------------------------------------------------- task_dod ---
func (q *Queries) SetTaskDodItem(ctx context.Context, arg SetTaskDodItemParams) (TaskDod, error) {
	row := q.db.QueryRow(ctx, setTaskDodItem,
		arg.TaskID,
		arg.Position,
		arg.Label,
		arg.Done,
	)
	var i TaskDod
	err := row.Scan(
		&i.TaskID,
		&i.Position,
		&i.Label,
		&i.Done,
	)
	return i, err
}

const toggleTaskDodItem = `-- name: ToggleTaskDodItem :one
UPDATE task_dod
SET done = NOT done
WHERE task_id = $1 AND position = $2
RETURNING task_id, position, label, done
`

type ToggleTaskDodItemParams struct {
	TaskID   string `json:"taskId"`
	Position int32  `json:"position"`
}

func (q *Queries) ToggleTaskDodItem(ctx context.Context, arg ToggleTaskDodItemParams) (TaskDod, error) {
	row := q.db.QueryRow(ctx, toggleTaskDodItem, arg.TaskID, arg.Position)
	var i TaskDod
	err := row.Scan(
		&i.TaskID,
		&i.Position,
		&i.Label,
		&i.Done,
	)
	return i, err
}

const updateDecision = `-- name: UpdateDecision :one
UPDATE decisions
SET decided_on = $2,
    title      = $3,
    detail     = $4,
    owner      = $5,
    status     = $6,
    updated_at = now()
WHERE id = $1
RETURNING id, product_id, decided_on, title, detail, owner, status, created_at, updated_at
`

type UpdateDecisionParams struct {
	ID        string    `json:"id"`
	DecidedOn time.Time `json:"decidedOn"`
	Title     string    `json:"title"`
	Detail    string    `json:"detail"`
	Owner     string    `json:"owner"`
	Status    string    `json:"status"`
}

func (q *Queries) UpdateDecision(ctx context.Context, arg UpdateDecisionParams) (Decision, error) {
	row := q.db.QueryRow(ctx, updateDecision,
		arg.ID,
		arg.DecidedOn,
		arg.Title,
		arg.Detail,
		arg.Owner,
		arg.Status,
	)
	var i Decision
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.DecidedOn,
		&i.Title,
		&i.Detail,
		&i.Owner,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateMember = `-- name: UpdateMember :one
UPDATE members
SET name          = $2,
    email         = $3,
    role          = $4,
    role_label    = $5,
    skill_tags    = $6,
    allocation    = $7,
    capacity_days = $8,
    workload      = $9,
    status        = $10,
    updated_at    = now()
WHERE id = $1
RETURNING id, name, email, role, role_label, skill_tags, allocation, capacity_days, workload, status, created_at, updated_at
`

type UpdateMemberParams struct {
	ID           string   `json:"id"`
	Name         string   `json:"name"`
	Email        string   `json:"email"`
	Role         string   `json:"role"`
	RoleLabel    string   `json:"roleLabel"`
	SkillTags    []string `json:"skillTags"`
	Allocation   int32    `json:"allocation"`
	CapacityDays float64  `json:"capacityDays"`
	Workload     int32    `json:"workload"`
	Status       string   `json:"status"`
}

func (q *Queries) UpdateMember(ctx context.Context, arg UpdateMemberParams) (Member, error) {
	row := q.db.QueryRow(ctx, updateMember,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.Role,
		arg.RoleLabel,
		arg.SkillTags,
		arg.Allocation,
		arg.CapacityDays,
		arg.Workload,
		arg.Status,
	)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Role,
		&i.RoleLabel,
		&i.SkillTags,
		&i.Allocation,
		&i.CapacityDays,
		&i.Workload,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateReportQueueStatus = `-- name: UpdateReportQueueStatus :one
UPDATE report_queue
SET status     = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, title, product_id, client, type, template, due, status, created_at, updated_at
`

type UpdateReportQueueStatusParams struct {
	ID     string `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateReportQueueStatus(ctx context.Context, arg UpdateReportQueueStatusParams) (ReportQueue, error) {
	row := q.db.QueryRow(ctx, updateReportQueueStatus, arg.ID, arg.Status)
	var i ReportQueue
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.ProductID,
		&i.Client,
		&i.Type,
		&i.Template,
		&i.Due,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTask = `-- name: UpdateTask :one
UPDATE tasks
SET title           = $2,
    module_name     = $3,
    assignee_id     = $4,
    estimate        = $5,
    board_column    = $6,
    priority        = $7,
    blocked_reason  = $8,
    blocked_days    = $9,
    off_goal        = $10,
    updated_at      = now()
WHERE id = $1
RETURNING id, sprint_id, backlog_item_id, title, module_name, assignee_id, estimate, board_column, priority, blocked_reason, blocked_days, off_goal, created_at, updated_at
`

type UpdateTaskParams struct {
	ID            string  `json:"id"`
	Title         string  `json:"title"`
	ModuleName    string  `json:"moduleName"`
	AssigneeID    *string `json:"assigneeId"`
	Estimate      int32   `json:"estimate"`
	BoardColumn   string  `json:"boardColumn"`
	Priority      string  `json:"priority"`
	BlockedReason *string `json:"blockedReason"`
	BlockedDays   *int32  `json:"blockedDays"`
	OffGoal       bool    `json:"offGoal"`
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTask,
		arg.ID,
		arg.Title,
		arg.ModuleName,
		arg.AssigneeID,
		arg.Estimate,
		arg.BoardColumn,
		arg.Priority,
		arg.BlockedReason,
		arg.BlockedDays,
		arg.OffGoal,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.SprintID,
		&i.BacklogItemID,
		&i.Title,
		&i.ModuleName,
		&i.AssigneeID,
		&i.Estimate,
		&i.BoardColumn,
		&i.Priority,
		&i.BlockedReason,
		&i.BlockedDays,
		&i.OffGoal,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertReportTemplate = `-- name: UpsertReportTemplate :one
INSERT INTO report_templates (id, name, audience, visibility, sections)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (id) DO UPDATE
SET name       = EXCLUDED.name,
    audience   = EXCLUDED.audience,
    visibility = EXCLUDED.visibility,
    sections   = EXCLUDED.sections,
    updated_at = now()
RETURNING id, name, audience, visibility, sections, created_at, updated_at
`

type UpsertReportTemplateParams struct {
	ID         string   `json:"id"`
	Name       string   `json:"name"`
	Audience   string   `json:"audience"`
	Visibility string   `json:"visibility"`
	Sections   []string `json:"sections"`
}

func (q *Queries) UpsertReportTemplate(ctx context.Context, arg UpsertReportTemplateParams) (ReportTemplate, error) {
	row := q.db.QueryRow(ctx, upsertReportTemplate,
		arg.ID,
		arg.Name,
		arg.Audience,
		arg.Visibility,
		arg.Sections,
	)
	var i ReportTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Audience,
		&i.Visibility,
		&i.Sections,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertRole = `-- name: UpsertRole :one
INSERT INTO roles (id, label, permissions)
VALUES ($1, $2, $3)
ON CONFLICT (id) DO UPDATE
SET label       = EXCLUDED.label,
    permissions = EXCLUDED.permissions
RETURNING id, label, permissions
`

type UpsertRoleParams struct {
	ID          string `json:"id"`
	Label       string `json:"label"`
	Permissions []byte `json:"permissions"`
}

func (q *Queries) UpsertRole(ctx context.Context, arg UpsertRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, upsertRole, arg.ID, arg.Label, arg.Permissions)
	var i Role
	err := row.Scan(&i.ID, &i.Label, &i.Permissions)
	return i, err
}

const upsertWorkspaceSettings = `-- name: UpsertWorkspaceSettings :one
INSERT INTO workspace_settings (id, name, settings, dod_template)
VALUES (TRUE, $1, $2, $3)
ON CONFLICT (id) DO UPDATE
SET name         = EXCLUDED.name,
    settings     = EXCLUDED.settings,
    dod_template = EXCLUDED.dod_template,
    updated_at   = now()
RETURNING id, name, settings, dod_template, updated_at
`

type UpsertWorkspaceSettingsParams struct {
	Name        string   `json:"name"`
	Settings    []byte   `json:"settings"`
	DodTemplate []string `json:"dodTemplate"`
}

func (q *Queries) UpsertWorkspaceSettings(ctx context.Context, arg UpsertWorkspaceSettingsParams) (WorkspaceSetting, error) {
	row := q.db.QueryRow(ctx, upsertWorkspaceSettings, arg.Name, arg.Settings, arg.DodTemplate)
	var i WorkspaceSetting
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Settings,
		&i.DodTemplate,
		&i.UpdatedAt,
	)
	return i, err
}
