// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearLoginFailures = `-- name: ClearLoginFailures :exec
UPDATE users
SET failed_login_count = 0, locked_until = NULL
WHERE id = $1
`

func (q *Queries) ClearLoginFailures(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, clearLoginFailures, id)
	return err
}

const consumePasswordResetToken = `-- name: ConsumePasswordResetToken :one
UPDATE password_reset_tokens
SET consumed_at = now()
WHERE token_hash = $1
  AND consumed_at IS NULL
  AND expires_at > now()
RETURNING token_hash, user_id
`

type ConsumePasswordResetTokenRow struct {
	TokenHash string `json:"tokenHash"`
	UserID    string `json:"userId"`
}

// Single-use and time-boxed, same conditional-UPDATE race guard as email
// verification: two submits of one link, only the first flips consumed_at.
func (q *Queries) ConsumePasswordResetToken(ctx context.Context, tokenHash string) (ConsumePasswordResetTokenRow, error) {
	row := q.db.QueryRow(ctx, consumePasswordResetToken, tokenHash)
	var i ConsumePasswordResetTokenRow
	err := row.Scan(&i.TokenHash, &i.UserID)
	return i, err
}

const consumeVerificationToken = `-- name: ConsumeVerificationToken :one
UPDATE email_verification_tokens
SET consumed_at = now()
WHERE token_hash = $1
  AND consumed_at IS NULL
  AND expires_at > now()
RETURNING token_hash, user_id
`

type ConsumeVerificationTokenRow struct {
	TokenHash string `json:"tokenHash"`
	UserID    string `json:"userId"`
}

// Consuming is a conditional UPDATE, not a read-then-write: two clicks on the
// same link race, and only the one that flips consumed_at from NULL matches a
// row. The loser gets no row and is told the link is already used.
func (q *Queries) ConsumeVerificationToken(ctx context.Context, tokenHash string) (ConsumeVerificationTokenRow, error) {
	row := q.db.QueryRow(ctx, consumeVerificationToken, tokenHash)
	var i ConsumeVerificationTokenRow
	err := row.Scan(&i.TokenHash, &i.UserID)
	return i, err
}

const createPasswordResetToken = `-- name: CreatePasswordResetToken :one

INSERT INTO password_reset_tokens (token_hash, user_id, expires_at)
VALUES ($1, $2, $3)
RETURNING token_hash, user_id, expires_at, consumed_at, created_at
`

type CreatePasswordResetTokenParams struct {
	TokenHash string             `json:"tokenHash"`
	UserID    string             `json:"userId"`
	ExpiresAt pgtype.Timestamptz `json:"expiresAt"`
}

// ------------------------------------------------------ password reset ---
func (q *Queries) CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) (PasswordResetToken, error) {
	row := q.db.QueryRow(ctx, createPasswordResetToken, arg.TokenHash, arg.UserID, arg.ExpiresAt)
	var i PasswordResetToken
	err := row.Scan(
		&i.TokenHash,
		&i.UserID,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one

INSERT INTO sessions (token_hash, user_id, expires_at)
VALUES ($1, $2, $3)
RETURNING token_hash, user_id, created_at, expires_at
`

type CreateSessionParams struct {
	TokenHash string             `json:"tokenHash"`
	UserID    string             `json:"userId"`
	ExpiresAt pgtype.Timestamptz `json:"expiresAt"`
}

// --------------------------------------------------------------- sessions ---
func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession, arg.TokenHash, arg.UserID, arg.ExpiresAt)
	var i Session
	err := row.Scan(
		&i.TokenHash,
		&i.UserID,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one

INSERT INTO users (id, email, password_hash, name, role, member_id, status)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING id, email, name, role, member_id, status, email_verified_at, created_at, updated_at
`

type CreateUserParams struct {
	ID           string  `json:"id"`
	Email        string  `json:"email"`
	PasswordHash string  `json:"passwordHash"`
	Name         string  `json:"name"`
	Role         string  `json:"role"`
	MemberID     *string `json:"memberId"`
	Status       string  `json:"status"`
}

type CreateUserRow struct {
	ID              string             `json:"id"`
	Email           string             `json:"email"`
	Name            string             `json:"name"`
	Role            string             `json:"role"`
	MemberID        *string            `json:"memberId"`
	Status          string             `json:"status"`
	EmailVerifiedAt pgtype.Timestamptz `json:"emailVerifiedAt"`
	CreatedAt       pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt       pgtype.Timestamptz `json:"updatedAt"`
}

// Users: authentication accounts, distinct from members.
//
// The password hash is confined to one query. Every read the API serialises
// returns an explicit column list without it, so there is no path by which a
// hash can be marshalled into a response; only GetUserForAuth selects it, and
// its result is never written to the client.
// status is the caller's decision because the two callers mean different
// things: self-registration starts 'pending' until the address is proven,
// while an admin-created account is born 'active' — the admin is vouching for
// it, and with no mailer a pending account created this way could never sign
// in at all. email_verified_at stays NULL either way until a real verify.
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.PasswordHash,
		arg.Name,
		arg.Role,
		arg.MemberID,
		arg.Status,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.MemberID,
		&i.Status,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createVerificationToken = `-- name: CreateVerificationToken :one

INSERT INTO email_verification_tokens (token_hash, user_id, expires_at)
VALUES ($1, $2, $3)
RETURNING token_hash, user_id, expires_at, consumed_at, created_at
`

type CreateVerificationTokenParams struct {
	TokenHash string             `json:"tokenHash"`
	UserID    string             `json:"userId"`
	ExpiresAt pgtype.Timestamptz `json:"expiresAt"`
}

// ------------------------------------------------ email verification ---
func (q *Queries) CreateVerificationToken(ctx context.Context, arg CreateVerificationTokenParams) (EmailVerificationToken, error) {
	row := q.db.QueryRow(ctx, createVerificationToken, arg.TokenHash, arg.UserID, arg.ExpiresAt)
	var i EmailVerificationToken
	err := row.Scan(
		&i.TokenHash,
		&i.UserID,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execrows
DELETE FROM sessions WHERE expires_at <= now()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredSessions)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSession = `-- name: DeleteSession :execrows
DELETE FROM sessions WHERE token_hash = $1
`

func (q *Queries) DeleteSession(ctx context.Context, tokenHash string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSession, tokenHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSessionsForUser = `-- name: DeleteSessionsForUser :execrows
DELETE FROM sessions WHERE user_id = $1
`

// Every session for a user — "log out everywhere", and the clean slate a
// password reset must leave (a stolen session must not outlive the reset).
func (q *Queries) DeleteSessionsForUser(ctx context.Context, userID string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSessionsForUser, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSessionUser = `-- name: GetSessionUser :one
SELECT u.id   AS user_id,
       u.email,
       u.name,
       u.role,
       u.member_id,
       r.permissions,
       s.expires_at
FROM sessions s
JOIN users u ON u.id = s.user_id
JOIN roles r ON r.id = u.role
WHERE s.token_hash = $1
  AND s.expires_at > now()
`

type GetSessionUserRow struct {
	UserID      string             `json:"userId"`
	Email       string             `json:"email"`
	Name        string             `json:"name"`
	Role        string             `json:"role"`
	MemberID    *string            `json:"memberId"`
	Permissions json.RawMessage    `json:"permissions"`
	ExpiresAt   pgtype.Timestamptz `json:"expiresAt"`
}

// The middleware query: one indexed lookup resolves the bearer token to the
// user and the permissions of their role. Expiry is checked here rather than
// in Go so an expired session and a bogus token are indistinguishable.
// password_hash is deliberately not selected (see TestPasswordHashNeverSerialised).
func (q *Queries) GetSessionUser(ctx context.Context, tokenHash string) (GetSessionUserRow, error) {
	row := q.db.QueryRow(ctx, getSessionUser, tokenHash)
	var i GetSessionUserRow
	err := row.Scan(
		&i.UserID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.MemberID,
		&i.Permissions,
		&i.ExpiresAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, email, name, role, member_id, status, email_verified_at, created_at, updated_at
FROM users
WHERE id = $1
`

type GetUserRow struct {
	ID              string             `json:"id"`
	Email           string             `json:"email"`
	Name            string             `json:"name"`
	Role            string             `json:"role"`
	MemberID        *string            `json:"memberId"`
	Status          string             `json:"status"`
	EmailVerifiedAt pgtype.Timestamptz `json:"emailVerifiedAt"`
	CreatedAt       pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt       pgtype.Timestamptz `json:"updatedAt"`
}

func (q *Queries) GetUser(ctx context.Context, id string) (GetUserRow, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i GetUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.MemberID,
		&i.Status,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, name, role, member_id, status, email_verified_at
FROM users
WHERE email = $1
`

type GetUserByEmailRow struct {
	ID              string             `json:"id"`
	Email           string             `json:"email"`
	Name            string             `json:"name"`
	Role            string             `json:"role"`
	MemberID        *string            `json:"memberId"`
	Status          string             `json:"status"`
	EmailVerifiedAt pgtype.Timestamptz `json:"emailVerifiedAt"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.MemberID,
		&i.Status,
		&i.EmailVerifiedAt,
	)
	return i, err
}

const getUserForAuth = `-- name: GetUserForAuth :one
SELECT id, email, password_hash, name, role, member_id, status,
       failed_login_count, locked_until
FROM users
WHERE email = $1
`

type GetUserForAuthRow struct {
	ID               string             `json:"id"`
	Email            string             `json:"email"`
	PasswordHash     string             `json:"passwordHash"`
	Name             string             `json:"name"`
	Role             string             `json:"role"`
	MemberID         *string            `json:"memberId"`
	Status           string             `json:"status"`
	FailedLoginCount int32              `json:"failedLoginCount"`
	LockedUntil      pgtype.Timestamptz `json:"lockedUntil"`
}

// The only query that returns the hash. Used to verify a password; its result
// must never be serialised to a client. Also carries the lockout state so login
// can refuse an account under a lock without a second round trip.
func (q *Queries) GetUserForAuth(ctx context.Context, email string) (GetUserForAuthRow, error) {
	row := q.db.QueryRow(ctx, getUserForAuth, email)
	var i GetUserForAuthRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Role,
		&i.MemberID,
		&i.Status,
		&i.FailedLoginCount,
		&i.LockedUntil,
	)
	return i, err
}

const getVerificationToken = `-- name: GetVerificationToken :one
SELECT token_hash, user_id, expires_at, consumed_at
FROM email_verification_tokens
WHERE token_hash = $1
`

type GetVerificationTokenRow struct {
	TokenHash  string             `json:"tokenHash"`
	UserID     string             `json:"userId"`
	ExpiresAt  pgtype.Timestamptz `json:"expiresAt"`
	ConsumedAt pgtype.Timestamptz `json:"consumedAt"`
}

func (q *Queries) GetVerificationToken(ctx context.Context, tokenHash string) (GetVerificationTokenRow, error) {
	row := q.db.QueryRow(ctx, getVerificationToken, tokenHash)
	var i GetVerificationTokenRow
	err := row.Scan(
		&i.TokenHash,
		&i.UserID,
		&i.ExpiresAt,
		&i.ConsumedAt,
	)
	return i, err
}

const invalidateUserPasswordResetTokens = `-- name: InvalidateUserPasswordResetTokens :exec
UPDATE password_reset_tokens
SET consumed_at = now()
WHERE user_id = $1 AND consumed_at IS NULL
`

// A fresh request invalidates any outstanding link, so only the newest works.
func (q *Queries) InvalidateUserPasswordResetTokens(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, invalidateUserPasswordResetTokens, userID)
	return err
}

const invalidateUserVerificationTokens = `-- name: InvalidateUserVerificationTokens :exec
UPDATE email_verification_tokens
SET consumed_at = now()
WHERE user_id = $1 AND consumed_at IS NULL
`

// Called before issuing a new link, so an earlier mail cannot still be used.
func (q *Queries) InvalidateUserVerificationTokens(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, invalidateUserVerificationTokens, userID)
	return err
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, name, role, member_id, status, email_verified_at, created_at, updated_at
FROM users
ORDER BY email, id
LIMIT $2 OFFSET $1
`

type ListUsersParams struct {
	Off int32 `json:"off"`
	Lim int32 `json:"lim"`
}

type ListUsersRow struct {
	ID              string             `json:"id"`
	Email           string             `json:"email"`
	Name            string             `json:"name"`
	Role            string             `json:"role"`
	MemberID        *string            `json:"memberId"`
	Status          string             `json:"status"`
	EmailVerifiedAt pgtype.Timestamptz `json:"emailVerifiedAt"`
	CreatedAt       pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt       pgtype.Timestamptz `json:"updatedAt"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersRow{}
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.Role,
			&i.MemberID,
			&i.Status,
			&i.EmailVerifiedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markUserVerified = `-- name: MarkUserVerified :one
UPDATE users
SET status            = CASE WHEN status = 'pending' THEN 'active' ELSE status END,
    email_verified_at = COALESCE(email_verified_at, now()),
    updated_at        = now()
WHERE id = $1
RETURNING id, email, name, role, member_id, status, email_verified_at
`

type MarkUserVerifiedRow struct {
	ID              string             `json:"id"`
	Email           string             `json:"email"`
	Name            string             `json:"name"`
	Role            string             `json:"role"`
	MemberID        *string            `json:"memberId"`
	Status          string             `json:"status"`
	EmailVerifiedAt pgtype.Timestamptz `json:"emailVerifiedAt"`
}

func (q *Queries) MarkUserVerified(ctx context.Context, id string) (MarkUserVerifiedRow, error) {
	row := q.db.QueryRow(ctx, markUserVerified, id)
	var i MarkUserVerifiedRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.MemberID,
		&i.Status,
		&i.EmailVerifiedAt,
	)
	return i, err
}

const recordFailedLogin = `-- name: RecordFailedLogin :one

UPDATE users
SET failed_login_count = failed_login_count + 1,
    locked_until = CASE
        WHEN failed_login_count + 1 >= $1::int
        THEN now() + make_interval(secs => $2::int)
        ELSE locked_until
    END
WHERE id = $3
RETURNING failed_login_count, locked_until
`

type RecordFailedLoginParams struct {
	Threshold   int32  `json:"threshold"`
	LockSeconds int32  `json:"lockSeconds"`
	ID          string `json:"id"`
}

type RecordFailedLoginRow struct {
	FailedLoginCount int32              `json:"failedLoginCount"`
	LockedUntil      pgtype.Timestamptz `json:"lockedUntil"`
}

// --------------------------------------------------------- login lockout ---
// Count one failure and, at the threshold, set the lock. The CASE keeps it one
// statement: no read-modify-write race between concurrent wrong guesses.
func (q *Queries) RecordFailedLogin(ctx context.Context, arg RecordFailedLoginParams) (RecordFailedLoginRow, error) {
	row := q.db.QueryRow(ctx, recordFailedLogin, arg.Threshold, arg.LockSeconds, arg.ID)
	var i RecordFailedLoginRow
	err := row.Scan(&i.FailedLoginCount, &i.LockedUntil)
	return i, err
}

const setUserPassword = `-- name: SetUserPassword :exec
UPDATE users
SET password_hash = $1,
    failed_login_count = 0,
    locked_until = NULL,
    updated_at = now()
WHERE id = $2
`

type SetUserPasswordParams struct {
	PasswordHash string `json:"passwordHash"`
	ID           string `json:"id"`
}

func (q *Queries) SetUserPassword(ctx context.Context, arg SetUserPasswordParams) error {
	_, err := q.db.Exec(ctx, setUserPassword, arg.PasswordHash, arg.ID)
	return err
}
