// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeVerificationToken = `-- name: ConsumeVerificationToken :one
UPDATE email_verification_tokens
SET consumed_at = now()
WHERE token_hash = $1
  AND consumed_at IS NULL
  AND expires_at > now()
RETURNING token_hash, user_id
`

type ConsumeVerificationTokenRow struct {
	TokenHash string `json:"tokenHash"`
	UserID    string `json:"userId"`
}

// Consuming is a conditional UPDATE, not a read-then-write: two clicks on the
// same link race, and only the one that flips consumed_at from NULL matches a
// row. The loser gets no row and is told the link is already used.
func (q *Queries) ConsumeVerificationToken(ctx context.Context, tokenHash string) (ConsumeVerificationTokenRow, error) {
	row := q.db.QueryRow(ctx, consumeVerificationToken, tokenHash)
	var i ConsumeVerificationTokenRow
	err := row.Scan(&i.TokenHash, &i.UserID)
	return i, err
}

const createSession = `-- name: CreateSession :one

INSERT INTO sessions (token_hash, user_id, expires_at)
VALUES ($1, $2, $3)
RETURNING token_hash, user_id, created_at, expires_at
`

type CreateSessionParams struct {
	TokenHash string             `json:"tokenHash"`
	UserID    string             `json:"userId"`
	ExpiresAt pgtype.Timestamptz `json:"expiresAt"`
}

// --------------------------------------------------------------- sessions ---
func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession, arg.TokenHash, arg.UserID, arg.ExpiresAt)
	var i Session
	err := row.Scan(
		&i.TokenHash,
		&i.UserID,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one

INSERT INTO users (id, email, password_hash, name, role, member_id)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, email, name, role, member_id, status, email_verified_at, created_at, updated_at
`

type CreateUserParams struct {
	ID           string  `json:"id"`
	Email        string  `json:"email"`
	PasswordHash string  `json:"passwordHash"`
	Name         string  `json:"name"`
	Role         string  `json:"role"`
	MemberID     *string `json:"memberId"`
}

type CreateUserRow struct {
	ID              string             `json:"id"`
	Email           string             `json:"email"`
	Name            string             `json:"name"`
	Role            string             `json:"role"`
	MemberID        *string            `json:"memberId"`
	Status          string             `json:"status"`
	EmailVerifiedAt pgtype.Timestamptz `json:"emailVerifiedAt"`
	CreatedAt       pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt       pgtype.Timestamptz `json:"updatedAt"`
}

// Users: authentication accounts, distinct from members.
//
// The password hash is confined to one query. Every read the API serialises
// returns an explicit column list without it, so there is no path by which a
// hash can be marshalled into a response; only GetUserForAuth selects it, and
// its result is never written to the client.
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.PasswordHash,
		arg.Name,
		arg.Role,
		arg.MemberID,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.MemberID,
		&i.Status,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createVerificationToken = `-- name: CreateVerificationToken :one

INSERT INTO email_verification_tokens (token_hash, user_id, expires_at)
VALUES ($1, $2, $3)
RETURNING token_hash, user_id, expires_at, consumed_at, created_at
`

type CreateVerificationTokenParams struct {
	TokenHash string             `json:"tokenHash"`
	UserID    string             `json:"userId"`
	ExpiresAt pgtype.Timestamptz `json:"expiresAt"`
}

// ------------------------------------------------ email verification ---
func (q *Queries) CreateVerificationToken(ctx context.Context, arg CreateVerificationTokenParams) (EmailVerificationToken, error) {
	row := q.db.QueryRow(ctx, createVerificationToken, arg.TokenHash, arg.UserID, arg.ExpiresAt)
	var i EmailVerificationToken
	err := row.Scan(
		&i.TokenHash,
		&i.UserID,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execrows
DELETE FROM sessions WHERE expires_at <= now()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredSessions)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSession = `-- name: DeleteSession :execrows
DELETE FROM sessions WHERE token_hash = $1
`

func (q *Queries) DeleteSession(ctx context.Context, tokenHash string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSession, tokenHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSessionUser = `-- name: GetSessionUser :one
SELECT u.id   AS user_id,
       u.email,
       u.name,
       u.role,
       u.member_id,
       r.permissions,
       s.expires_at
FROM sessions s
JOIN users u ON u.id = s.user_id
JOIN roles r ON r.id = u.role
WHERE s.token_hash = $1
  AND s.expires_at > now()
`

type GetSessionUserRow struct {
	UserID      string             `json:"userId"`
	Email       string             `json:"email"`
	Name        string             `json:"name"`
	Role        string             `json:"role"`
	MemberID    *string            `json:"memberId"`
	Permissions json.RawMessage    `json:"permissions"`
	ExpiresAt   pgtype.Timestamptz `json:"expiresAt"`
}

// The middleware query: one indexed lookup resolves the bearer token to the
// user and the permissions of their role. Expiry is checked here rather than
// in Go so an expired session and a bogus token are indistinguishable.
// password_hash is deliberately not selected (see TestPasswordHashNeverSerialised).
func (q *Queries) GetSessionUser(ctx context.Context, tokenHash string) (GetSessionUserRow, error) {
	row := q.db.QueryRow(ctx, getSessionUser, tokenHash)
	var i GetSessionUserRow
	err := row.Scan(
		&i.UserID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.MemberID,
		&i.Permissions,
		&i.ExpiresAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, email, name, role, member_id, status, email_verified_at, created_at, updated_at
FROM users
WHERE id = $1
`

type GetUserRow struct {
	ID              string             `json:"id"`
	Email           string             `json:"email"`
	Name            string             `json:"name"`
	Role            string             `json:"role"`
	MemberID        *string            `json:"memberId"`
	Status          string             `json:"status"`
	EmailVerifiedAt pgtype.Timestamptz `json:"emailVerifiedAt"`
	CreatedAt       pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt       pgtype.Timestamptz `json:"updatedAt"`
}

func (q *Queries) GetUser(ctx context.Context, id string) (GetUserRow, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i GetUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.MemberID,
		&i.Status,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, name, role, member_id, status, email_verified_at
FROM users
WHERE email = $1
`

type GetUserByEmailRow struct {
	ID              string             `json:"id"`
	Email           string             `json:"email"`
	Name            string             `json:"name"`
	Role            string             `json:"role"`
	MemberID        *string            `json:"memberId"`
	Status          string             `json:"status"`
	EmailVerifiedAt pgtype.Timestamptz `json:"emailVerifiedAt"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.MemberID,
		&i.Status,
		&i.EmailVerifiedAt,
	)
	return i, err
}

const getUserForAuth = `-- name: GetUserForAuth :one
SELECT id, email, password_hash, name, role, member_id, status
FROM users
WHERE email = $1
`

type GetUserForAuthRow struct {
	ID           string  `json:"id"`
	Email        string  `json:"email"`
	PasswordHash string  `json:"passwordHash"`
	Name         string  `json:"name"`
	Role         string  `json:"role"`
	MemberID     *string `json:"memberId"`
	Status       string  `json:"status"`
}

// The only query that returns the hash. Used to verify a password; its result
// must never be serialised to a client.
func (q *Queries) GetUserForAuth(ctx context.Context, email string) (GetUserForAuthRow, error) {
	row := q.db.QueryRow(ctx, getUserForAuth, email)
	var i GetUserForAuthRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Role,
		&i.MemberID,
		&i.Status,
	)
	return i, err
}

const getVerificationToken = `-- name: GetVerificationToken :one
SELECT token_hash, user_id, expires_at, consumed_at
FROM email_verification_tokens
WHERE token_hash = $1
`

type GetVerificationTokenRow struct {
	TokenHash  string             `json:"tokenHash"`
	UserID     string             `json:"userId"`
	ExpiresAt  pgtype.Timestamptz `json:"expiresAt"`
	ConsumedAt pgtype.Timestamptz `json:"consumedAt"`
}

func (q *Queries) GetVerificationToken(ctx context.Context, tokenHash string) (GetVerificationTokenRow, error) {
	row := q.db.QueryRow(ctx, getVerificationToken, tokenHash)
	var i GetVerificationTokenRow
	err := row.Scan(
		&i.TokenHash,
		&i.UserID,
		&i.ExpiresAt,
		&i.ConsumedAt,
	)
	return i, err
}

const invalidateUserVerificationTokens = `-- name: InvalidateUserVerificationTokens :exec
UPDATE email_verification_tokens
SET consumed_at = now()
WHERE user_id = $1 AND consumed_at IS NULL
`

// Called before issuing a new link, so an earlier mail cannot still be used.
func (q *Queries) InvalidateUserVerificationTokens(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, invalidateUserVerificationTokens, userID)
	return err
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, name, role, member_id, status, email_verified_at, created_at, updated_at
FROM users
ORDER BY email, id
LIMIT $2 OFFSET $1
`

type ListUsersParams struct {
	Off int32 `json:"off"`
	Lim int32 `json:"lim"`
}

type ListUsersRow struct {
	ID              string             `json:"id"`
	Email           string             `json:"email"`
	Name            string             `json:"name"`
	Role            string             `json:"role"`
	MemberID        *string            `json:"memberId"`
	Status          string             `json:"status"`
	EmailVerifiedAt pgtype.Timestamptz `json:"emailVerifiedAt"`
	CreatedAt       pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt       pgtype.Timestamptz `json:"updatedAt"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersRow{}
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.Role,
			&i.MemberID,
			&i.Status,
			&i.EmailVerifiedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markUserVerified = `-- name: MarkUserVerified :one
UPDATE users
SET status            = CASE WHEN status = 'pending' THEN 'active' ELSE status END,
    email_verified_at = COALESCE(email_verified_at, now()),
    updated_at        = now()
WHERE id = $1
RETURNING id, email, name, role, member_id, status, email_verified_at
`

type MarkUserVerifiedRow struct {
	ID              string             `json:"id"`
	Email           string             `json:"email"`
	Name            string             `json:"name"`
	Role            string             `json:"role"`
	MemberID        *string            `json:"memberId"`
	Status          string             `json:"status"`
	EmailVerifiedAt pgtype.Timestamptz `json:"emailVerifiedAt"`
}

func (q *Queries) MarkUserVerified(ctx context.Context, id string) (MarkUserVerifiedRow, error) {
	row := q.db.QueryRow(ctx, markUserVerified, id)
	var i MarkUserVerifiedRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.MemberID,
		&i.Status,
		&i.EmailVerifiedAt,
	)
	return i, err
}
